### ISSUE TITLE
Cannot build due to these errors which I'm not sure what to do about.

### ISSUE THREAD

**Issue by kanaanayt** [be5invis/Iosevka#1108]
> iosevka@7.0.3 build /Users/kanaan/Documents/Iosevka-master
> node utility/ensure-verda-exists && verda -f verdafile.js "contents::iosevka-custom"

× Fail External dependency <ttfautohint>, needed for building hinted font, does not exist.
♦ Create WebFont CSS iosevka-custom -> dist/iosevka-custom/iosevka-custom.css 
Building process terminated.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@7.0.3 build: `node utility/ensure-verda-exists && verda -f verdafile.js "contents::iosevka-custom"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iosevka@7.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kanaan/.npm/_logs/2021-06-04T07_28_32_068Z-debug.log

ttfautohint was installed through MacPorts

**Comment by kanaanayt** [comment]
``
[buildPlans.iosevka-custom]      # <iosevka-custom> is your plan name
family = "Iosevka Custom"        # Font menu family name
spacing = "fixed"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"                  # Optional; Values: `sans` or `slab`

###################################################################################################
# Configure variants

# Optional; Whether to inherit a `ss##` variant
#[buildPlans.iosevka-custom.variants]
#inherits = "ss14"


# Optional; Configure single character's variant
[buildPlans.iosevka-custom.variants.design]
r = 'earless-corner'
four = 'semi-open-non-crossing'
six = 'closed-contour'
nine = 'open-contour'
m = 'earless-corner-double-arch'
n = 'earless-corner-straight'
a = 'doublestorey-toothless-corner'
i = 'serifed-tailed'
l = 'serifed-flat-tailed'
u = 'toothless-corner'
y = 'cursive'
capital-g = 'toothless'
capital-j = 'serifless'
capital-m = 'flat-bottom'
capital-q = 'straight'
g = 'earless-corner'
w = 'straight-flat-top'
asterisk = 'hexhigh'
number-sign = 'slanted'
at = 'fourfold'
dollar = 'through'
percent = 'rings-connected'

# End variant section
##################################################################################################

###################################################################################################
# Configure ligations


# End ligation section			
###################################################################################################


###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.

[buildPlans.iosevka-custom.weights.regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.iosevka-custom.weights.book]
shape = 400
menu  = 450  # Use 450 here to name the font's weight "Book"
css   = 450

[buildPlans.iosevka-custom.weights.bold]
shape = 400
menu  = 700
css   = 700

#[buildPlans.iosevka-custom.weights.extended]
#shape = 400
#menu  = 400
#css   = 400

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slopes would be built.


# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevka-custom.widths.normal]
shape = 576        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

[buildPlans.iosevka-custom.widths.extended]
shape = 576
menu  = 7
css   = "expanded"

# End width section
###################################################################################################

###################################################################################################
# Character Exclusion
# Specify character ranges in the section below to exclude certain characters from the font being
# built. Remove this section when this feature is not needed.

#[buildPlans.iosevka-custom.exclude-chars]
#ranges = [[10003, 10008]]

# End character exclusion
###################################################################################################

###################################################################################################
# Compatibility Ligatures
# Certain applications like Emacs does not support proper programming liagtures provided by
# OpenType, but can support ligatures provided by PUA codepoints. Therefore you can edit the
# following section to build PUA characters that are generated from the OpenType ligatures.
# Remove this section when compatibility ligatures are not needed.


# End compatibility ligatures section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

#[buildPlans.iosevka-custom.metric-override]
#leading = 1250
#winMetricAscenderPad = 0
#winMetricDescenderPad = 0
#powerlineScaleY = 1
#powerlineScaleX = 1
#powerlineShiftY = 0
#powerlineShiftX = 0

# End metric override section
####################################################################################################

``

**Comment by alexeyten** [comment]
What does command `which ttfautohint` show?

**Comment by kanaanayt** [comment]
Alright it wasn't showing anything at first. Fixed that.
But I keep getting the following for every single font variant:

`` × Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-boldoblique.ttf":
 Error: Error: Composite {user} cannot be resolved: a,doublestorey-toothless-corner.
    at Composite.decompose (/Users/kanaan/Documents/Iosevka-master/font-src/support/variant-data.js:169:19)
    at Composite.resolve (/Users/kanaan/Documents/Iosevka-master/font-src/support/variant-data.js:184:39)
    at Object.applyVariantData [as apply] (/Users/kanaan/Documents/Iosevka-master/font-src/support/variant-data.js:21:17)
    at createParaImpl (/Users/kanaan/Documents/Iosevka-master/font-src/index.js:45:15)
    at reinit (/Users/kanaan/Documents/Iosevka-master/font-src/index.js:64:16)
    at main (/Users/kanaan/Documents/Iosevka-master/font-src/index.js:19:53)
    at ChildProcess.<anonymous> (/Users/kanaan/Documents/Iosevka-master/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:376:20)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) ``

**Comment by kanaanayt** [comment]
I have a toml file from a year ago. They don't match since Iosevka was updated. That was the issue all along. Thanks a lot.

**Comment by alexeyten** [comment]
Some character variants have been renamed between versions.
In particular `doublestorey-toothless-corner` become `double-storey-toothless-corner`.

**Comment by alexeyten** [comment]
I use command like `git log -p -S doublestorey-toothless-corner` to find out renames

**Comment by be5invis** [comment]
Closing since it is a configuration mistake.
