### ISSUE TITLE
can't build 8.0.0 "slope definition of upright is invalid"

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#1166]
Describe your problem here. Provide pictures and files if necessary.

---

* Your font version: 8.0.0
* Your font variant: custom
* Your operating system: windows 10

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 14.10.1

* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-habamax]
family      = "Iosevka Habamax"
spacing     = "term"
no-cv-ss    = true
no-ligation = true
serifs      = "sans"


[buildPlans.iosevka-habamax.variants.design]
three     = 'flattop'
four      = 'open-non-crossing'
asterisk  = 'hex-low'
bar       = 'force-upright'
percent   = 'rings-continuous-slash'


[buildPlans.iosevka-habamax.variants.italic]
k = 'straight-serifless'


[buildPlans.iosevka-habamax.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS


[buildPlans.iosevka-habamax.weights.bold]
shape = 700
menu  = 700
css   = 700


[buildPlans.iosevka-habamax.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"


[buildPlans.iosevka-habamax.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"


[buildPlans.iosevka-habamax.widths.normal]
shape = 600
menu  = 5
css   = "normal"

```
* The detailed error log:
```
 > iosevka@8.0.0 build D:\prj\fonts\Iosevka
> node utility/ensure-verda-exists && verda -f verdafile.js "ttf::iosevka-habamax"

× Error Unhandled exception when building "Builtin::Computed::metadata:build-plans":
 TypeError: Slope definition of upright is invalid.
    at wwsDefValidate (D:\prj\fonts\Iosevka\verdafile.js:936:9)
    at getSuffixMappingItem (D:\prj\fonts\Iosevka\verdafile.js:233:19)
    at getSuffixMapping (D:\prj\fonts\Iosevka\verdafile.js:224:23)
    at OracleRule.FRecipe (D:\prj\fonts\Iosevka\verdafile.js:137:25)
    at async OracleRule.build (D:\prj\fonts\Iosevka\node_modules\verda\lib\rule-types\oracle.js:20:24)
Building process terminated.
TypeError: Slope definition of upright is invalid.
    at wwsDefValidate (D:\prj\fonts\Iosevka\verdafile.js:936:9)
    at getSuffixMappingItem (D:\prj\fonts\Iosevka\verdafile.js:233:19)
    at getSuffixMapping (D:\prj\fonts\Iosevka\verdafile.js:224:23)
    at OracleRule.FRecipe (D:\prj\fonts\Iosevka\verdafile.js:137:25)
    at async OracleRule.build (D:\prj\fonts\Iosevka\node_modules\verda\lib\rule-types\oracle.js:20:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@8.0.0 build: `node utility/ensure-verda-exists && verda -f verdafile.js "ttf::iosevka-habamax"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iosevka@8.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\maksim.kim\AppData\Roaming\npm-cache\_logs\2021-07-25T15_20_53_834Z-debug.log
```

**Comment by be5invis** [comment]
Unable to reproduce.

**Comment by be5invis** [comment]
This error indicates that `buildPlans.iosevka-habamax.slopes.upright` is either missing or being a string. You can try run `npm run clean` and try rebuild.
