### ISSUE TITLE
Custom build error

### ISSUE THREAD

**Issue by nobk** [be5invis/Iosevka#1173]
Custom build with latest customizer https://typeof.net/Iosevka/customizer generated private-build-plans.toml

```
  [buildPlans.iosevka-custom.slopes]
  upright = "normal"
  italic = "italic"

```
failed, syntax changed?

* Your font version: 8.0.2
* Your font variant: SS13
* Your operating system (name and version): docker avivace/iosevka-build

If you have problem when building Iosevka, please provide these information:

* Your `private-build-plans.toml`, if present:

```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss13"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-custom.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

  [buildPlans.iosevka-custom.slopes]
  upright = "normal"
  italic = "italic"
```
* The detailed error log:
```
Building process terminated.
TypeError: Slope definition of upright is invalid.
    at wwsDefValidate (/tmp/build/Iosevka-8.0.2/verdafile.js:941:9)
    at getSuffixMappingItem (/tmp/build/Iosevka-8.0.2/verdafile.js:233:19)
    at getSuffixMapping (/tmp/build/Iosevka-8.0.2/verdafile.js:224:23)
    at OracleRule.FRecipe (/tmp/build/Iosevka-8.0.2/verdafile.js:137:25)
    at async OracleRule.build (/tmp/build/Iosevka-8.0.2/node_modules/verda/lib/rule-types/oracle.js:20:24)
npm ERR! code ELIFECYCLE

Building process terminated.
TypeError: Slope definition of italic is invalid.
    at wwsDefValidate (/tmp/build/Iosevka-8.0.2/verdafile.js:941:9)
    at getSuffixMappingItem (/tmp/build/Iosevka-8.0.2/verdafile.js:233:19)
    at getSuffixMapping (/tmp/build/Iosevka-8.0.2/verdafile.js:224:23)
    at OracleRule.FRecipe (/tmp/build/Iosevka-8.0.2/verdafile.js:137:25)
    at async OracleRule.build (/tmp/build/Iosevka-8.0.2/node_modules/verda/lib/rule-types/oracle.js:20:24)
npm ERR! code ELIFECYCLE

```

**Comment by be5invis** [comment]
> syntax changed?

Yes. I'll update the customizer

**Comment by be5invis** [comment]
customizer fixed. Closing.
