### ISSUE TITLE
Dependency 'ttfautohint' causing some issues

### ISSUE THREAD

**Issue by BenjamienSD** [be5invis/Iosevka#1201]
Using regular npm install causes errors for ttfautohint.  
Adding the latest ttfautohint executable downloaded from freetype.org (version 1.8.4) to the root folder fixes the issue.

---

* Windows 10 20H2

* Node.js: v14.17.5

```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-d = "more-rounded-serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-hooked"
capital-j = "serifed-symmetric"
capital-k = "curly-serifless"
capital-p = "closed"
capital-q = "curly-tailed"
capital-r = "curly"
capital-u = "toothed"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
a = "double-storey-serifless"
c = "serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "double-storey-open"
i = "tailed-serifed"
j = "serifed"
k = "curly-serifless"
l = "tailed-serifed"
r = "top-serifed"
t = "standard"
u = "toothed"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "straight-turn"
one = "base"
two = "straight-neck"
four = "semi-open"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "straight-serifed"
nine = "open-contour"
paren = "flat-arc"
brace = "straight"
at = "fourfold"
lig-ltgteq = "slanted"
ascii-single-quote = "raised-comma"
ascii-grave = "straight"

[buildPlans.iosevka-custom.ligations]
inherits = "javascript"
```

* The detailed error log:
Doing the initial npm install:

```
> ttfautohint@1.3.0 install G:\documents\Iosevka Custom 2021\node_modules\ttfautohint
> node install

# [ttfautohint] Getting source packages
# [ttfautohint] Extracting
# [ttfautohint] Compiling binaries
(node:1256) UnhandledPromiseRejectionWarning: Error: Command failed: ./configure --disable-shared --enable-static --prefix="C:\Users\Admin\AppData\Roaming\npm-cache\enteocode\ttfautohint\build" --without-bzip2 --without-harfbuzz --without-png --without-zlib CFLAGS="-fPIC -g -O3 -IC:\Users\Admin\AppData\Roaming\npm-cache\enteocode\ttfautohint\build/include" CXXFLAGS="-fPIC -g -O3 -IC:\Users\Admin\AppData\Roaming\npm-cache\enteocode\ttfautohint\build/include" LDFLAGS="-fPIC -LC:\Users\Admin\AppData\Roaming\npm-cache\enteocode\ttfautohint\build/lib -LC:\Users\Admin\AppData\Roaming\npm-cache\enteocode\ttfautohint\build/lib64" PKG_CONFIG=" " && make && make install
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:1256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN iosevka@10.1.0 No repository field.
npm WARN iosevka@10.1.0 No license field.

added 314 packages from 156 contributors and audited 315 packages in 33.1s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by be5invis** [comment]
Well, `ttfautohint` should not install through NPM. You could grab its executable from [its website](https://www.freetype.org/ttfautohint/) and put it somewhere accessible from your PATH.

**Comment by BenjamienSD** [comment]
> You could grab its executable from its website and put it somewhere accessible from your PATH.  

That's what I did. I just assumed it would get added through npm. My bad. Turns out I didn't read the docs thoroughly enough.  
User error, the user apologizes.

Thank you for this font.

**Comment by Ahmed-Al-Najjar** [comment]
Hey [be5invis](https://github.com/be5invis) could you guide me through installing ttfautohint
