### ISSUE TITLE
[14.0.1] Unable to create custom build

### ISSUE THREAD

**Issue by Ypnose** [be5invis/Iosevka#1312]
Hello,

Since `14.0.1` (no issue with `14.0.0`), I am unable to launch a custom build. I have this error :

```
npm run build -- ttf::iosevka-custom

> iosevka@14.0.1 build
> node utility/ensure-verda-exists && verda -f verdafile.js "ttf::iosevka-custom"


/home/foo/Iosevka-14.0.1/verdafile.js:216
		excludedCharRanges: bp["exclude-chars"]?.ranges
		                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/foo/Iosevka-14.0.1/node_modules/verda/lib/cli/verda.js:19:89
    at async main (/home/foo/Iosevka-14.0.1/node_modules/verda/lib/cli/verda.js:19:28)
npm ERR! code 1
npm ERR! path /home/foo/Iosevka-14.0.1
npm ERR! command failed
npm ERR! command sh -c node utility/ensure-verda-exists && verda -f verdafile.js "ttf::iosevka-custom"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/foo/.npm/_logs/2022-02-21T15_37_31_332Z-debug.log
```
It might be related to 5b08cb294217c6298.

---

* Your font version: 14.0.1
* Your font variant: iosevka-custom
* Your operating system (name and version): Ubuntu 21.10

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 12.22.5
* Your _otfcc_ version: git
* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-custom]
family  = "Iosevka Term Custom"
spacing = "term"
serifs  = "sans"
no-cv-ss = "true"

[buildPlans.iosevka-custom.variants.design]
capital-a = "curly-serifless"
f = "flat-hook"
percent = "dots"
lig-ltgteq = "slanted"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0             # Angle in degrees. Valid range [0, 15]
shape = "upright"     # Slope grade used for shape selection.  'upright' | 'oblique' | 'italic'
menu  = "upright"     # Slope grade used for naming.           'upright' | 'oblique' | 'italic'
css   = "normal"      # Slope grade used for webfont CSS.      'normal'  | 'oblique' | 'italic'

[buildPlans.iosevka-custom.widths.normal]
shape = 600        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.
```
* The detailed error log (see above)

**Comment by alexeyten** [comment]
I guess you should upgrade node

**Comment by be5invis** [comment]
You need to upgrade the version of Node.JS.
Resolve as external.

**Comment by Ypnose** [comment]
Thanks to both of you, it's fine with nodejs LTS. I see you updated the minimal version required too.
