### ISSUE TITLE
Windows applications with older .NET Framwork version throwing execption on startup after installing `Iosevka` (super ttc)

### ISSUE THREAD

**Issue by horror-proton** [be5invis/Iosevka#1373]
~This sounds strange, but it does reproduce.~

After installing default version of `Iosevka` (for all users) with super ttc (e.g. [Iosevka — Monospace, Default](https://github.com/be5invis/Iosevka/releases/download/v15.5.2/super-ttc-iosevka-15.5.2.zip)), 
GUI applications with .NET Framwork 3.5 would throw `TypeInitializationException` in `System.Windows.Media.FontFamily` on start up. 

Removing `Iosevka` from system fonts would fix this.

Stack trace: 
```cs
 at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.GetValueNames()
   at MS.Internal.FontCache.FontSourceCollection.SetFontSources()
   at MS.Internal.FontCache.FontSourceCollection.GetEnumerator()
   at MS.Internal.FontCache.FamilyCollection.BuildFamilyList(List`1& familyList, SortedDictionary`2& familyNameList, SortedList`2& frequentStrings)
   at MS.Internal.FontCache.FamilyCollection.MS.Internal.FontCache.IFontCacheElement.AddToCache(CheckedPointer newPointer, ElementCacher cacher)
   at MS.Internal.FontCache.HashTable.Lookup(IFontCacheElement e, Boolean add)
   at MS.Internal.FontCache.CacheManager.Lookup(IFontCacheElement e)
   at System.Windows.Media.FontFamily..cctor()
```

---

I was told that illegal characters in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts` wold result in the same exception. (ref. [Visual Studio setup crashes with an exception after the splash screen is shown](https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/fonts-cause-setup-crash), [How to Crash every WPF application](https://faithlife.codes/blog/2009/11/how_to_crash_every_wpf_application/) and https://github.com/Jamiras/RATools/issues/15)

Installing `Iosevka` would create someting like
```
"Iosevka Thin & Iosevka Term Thin & Iosevka Fixed Thin & Iosevka Thin Extended & Iosevka Term Thin Extended & Iosevka Fixed Thin Extended & Iosevka Thin Oblique & Iosevka Thin Italic & Iosevka Term Thin Oblique & Iosevka Term Thin Italic & Iosevka Fixed Thin O"="iosevka_0.ttc"
```
in the registry, nothing strange but perhaps it would be too long and exceed the maximum path length limitation of Windows.

An `IOException` was thrown when trying to access `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts` with
```cs
Microsoft.Win32.RegistryKey::GetValueNames() //  .NET Framwork version = 3.5
```
which works fine without `Iosevka` installed. 

---

I'm not sure if this is more a WPF/.NET issue, but I guess it would be better to document this somewhere. 🤔

---

* Your font version: 15.5.2
* Your font variant: default
* Your operating system (name and version): Windows 10 
* Your application using Iosevka: None (those mentioned above do not ***use*** the font, they crash as it installed in system)

**Comment by horror-proton** [comment]
Hmmm, I don't think this has anything to do with whether it is a super-TTC or not. 

As mentioned above, those application do not even **use** the font. They crash on listing value names of the registry key when start up, even without knowing the names and values are font names and files.

**Comment by horror-proton** [comment]
The value name was already truncated to 259 characters (by Windows?) `"... & Iosevka Fixed Thin O"`, manually truncatint the name to 255 characters `"... & Iosevka Fixed Th"` would also fix the problem.
