### ISSUE TITLE
Error building with `five=oblique-arched`

### ISSUE THREAD

**Issue by lshoravi** [be5invis/Iosevka#2019]
Describe your problem here. Provide pictures and files if necessary.

Building with `five=oblique-arched` gives the following error:

```
× Error Unhandled exception when building "Builtin::File::dist/iosevka-slate/ttf-unhinted/iosevka-slate-re
gular.ttf":
 Error: Error: Composite {user} cannot be resolved: five,oblique-flat.
    at Composite.decompose (file:///Users/linuss/.config/font/Iosevka/font-src/support/variant-data.mjs:23
4:19)
    at Composite.resolve (file:///Users/linuss/.config/font/Iosevka/font-src/support/variant-data.mjs:249:
39)
    at Module.apply (file:///Users/linuss/.config/font/Iosevka/font-src/support/variant-data.mjs:19:17)
    at createParaImpl (file:///Users/linuss/.config/font/Iosevka/font-src/index.mjs:62:15)
    at reinit (file:///Users/linuss/.config/font/Iosevka/font-src/index.mjs:74:16)
    at main (file:///Users/linuss/.config/font/Iosevka/font-src/index.mjs:24:15)
    at ChildProcess.<anonymous> (/Users/linuss/.config/font/Iosevka/node_modules/verda/lib/actions/nodejs/
command.js:53:31)
    at ChildProcess.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
---

* Your font version: (Release or git, version) git revision f6e57fb
* Your font variant: custom
* Your operating system (name and version): macOS 

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 20.6.1
* Your `params/parameters.toml`, paste if modified:
  ```
  paste here
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  paste here
  ```
* Your `private-build-plans.toml`, if present:
  ```
[buildPlans.iosevka-slate]
family = "Iosevka Slate"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-slate.variants.design]
capital-a = "straight-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-h = "serifless"
capital-j = "serifless"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "flat-bottom-serifless"
capital-n = "asymmetric-serifless"
capital-p = "closed-serifless"
capital-q = "curly-tailed"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-tailed"
b = "toothed-motion-serifed"
c = "serifless"
d = "tailed-serifed"
g = "double-storey"
h = "straight-top-left-serifed"
k = "straight-serifless"
l = "serifed"
m = "serifless"
n = "straight-serifless"
p = "eared-motion-serifed"
q = "straight-serifless"
r = "corner-hooked-serifless"
s = "serifless"
u = "toothed-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
lower-lambda = "straight-turn"
zero = "oval-slashed"
one = "no-base-long-top-serif"
two = "straight-neck"
three = "flat-top"
four = "semi-open-non-crossing"
five = "oblique-flat"
asterisk = "turn-hex-low"
underscore = "above-baseline"
paren = "normal"
brace = "curly-flat-boundary"
number-sign = "upright-tall"
at = "fourfold-solid-inner-tall"
dollar = "interrupted"
percent = "rings-continuous-slash"
ascii-single-quote = "raised-comma"
ascii-grave = "raised-turn-comma"
question = "corner"
lig-ltgteq = "slanted"

[buildPlans.iosevka-slate.variants.italic]
a = "single-storey-tailed"
f = "diagonal-tailed-crossbar-at-x-height"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
k = "straight-serifless"
l = "serifed-diagonal-tailed"
t = "diagonal-tailed"
y = "straight-serifless"
percent = "rings-continuous-slash"

  [buildPlans.iosevka-slate.ligations]
  inherits = "dlig"

[buildPlans.iosevka-slate.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-slate.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-slate.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-slate.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-slate.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-slate.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

  ```
* The detailed error log:
see above

**Comment by Logo121** [comment]
main branch is not updated for some reason?

Try the dev branch.

**Comment by jmcwilliams403** [comment]
> Try the dev branch.

or the prerelease branch, for something more stable

**Comment by be5invis** [comment]
Cleaned up `main`. 
Resolve as fixed.
