### ISSUE TITLE
Referencing default configuration in `private-build-plans.toml` is broken

### ISSUE THREAD

**Issue by mengelbrecht** [be5invis/Iosevka#2117]
Referencing the default configuration in `private-build-plans.toml` does not work anymore (worked with Iosevka 27.3.5).

---

* Your font version: 28.0.0
* Your font variant: custom
* Your operating system (name and version): Docker - Debian Unstable
* Your Node.js version: 21.4.0
* Your `private-build-plans.toml`, if present:
  ```
  [buildPlans.iosevka-test]
  family = "Iosevka Test"
  spacing = "normal"
  serifs = "sans"
  
  [buildPlans.iosevka-test.widths]
  normal = "default.normal"
  
  [buildPlans.iosevka-test.weights]
  medium = "default.medium"
  
  [buildPlans.iosevka-test.slopes]
  upright = "default.upright"
  ```
* The detailed error 
  ```
  [ERROR] Target Error Error: Invalid configuration 'default.medium' for weights.medium'
      at shimBpAspectKey (file:///builder/verdafile.mjs:1289:10)
      at shimBpAspect (file:///builder/verdafile.mjs:1279:3)
      at resolveWwsAspect (file:///builder/verdafile.mjs:1255:10)
      at resolveWws (file:///builder/verdafile.mjs:1245:15)
      at OracleRule.FRecipe (file:///builder/verdafile.mjs:145:3)
      at async OracleRule.build (/builder/node_modules/verda/lib/rule-types/oracle.js:20:24)
  
  ...
  
  [ERROR] Target Error Error: Invalid configuration 'default.normal' for widths.normal'
      at shimBpAspectKey (file:///builder/verdafile.mjs:1289:10)
      at shimBpAspect (file:///builder/verdafile.mjs:1279:3)
      at resolveWwsAspect (file:///builder/verdafile.mjs:1255:10)
      at resolveWws (file:///builder/verdafile.mjs:1246:14)
      at OracleRule.FRecipe (file:///builder/verdafile.mjs:145:3)
      at async OracleRule.build (/builder/node_modules/verda/lib/rule-types/oracle.js:20:24)
  
  ...
  
  [ERROR] Target Error Error: Invalid configuration 'default.upright' for slopes.upright'
      at shimBpAspectKey (file:///builder/verdafile.mjs:1289:10)
      at shimBpAspect (file:///builder/verdafile.mjs:1279:3)
      at resolveWwsAspect (file:///builder/verdafile.mjs:1255:10)
      at resolveWws (file:///builder/verdafile.mjs:1247:14)
      at OracleRule.FRecipe (file:///builder/verdafile.mjs:145:3)
      at async OracleRule.build (/builder/node_modules/verda/lib/rule-types/oracle.js:20:24)
  ```

**Comment by jmcwilliams403** [comment]
Named widths, weights, and slopes of the default configuration now start with capital letters.

**Comment by mengelbrecht** [comment]
Ah, thanks. It works 👍🏻
