### ISSUE TITLE
TypeError: Object #<Object> has no method 'hypot'

### ISSUE THREAD

**Issue by ElSebita** [be5invis/Iosevka#31]
Hello.
I followed the instructions, I installed everything including patel-c as global. `make` throws that error.
I installed `es6-math` as global, which is said to provide `Math.hypot` but still can't build.
Fedora 22.

```
/home/meneldur/Downloads/Iosevka-master/node_modules/libspiro-js/libspiro.js:218
		r[i].seg_ch = Math.hypot(dx, dy);
		                   ^
TypeError: Object #<Object> has no method 'hypot'
    at setup_path (/home/meneldur/Downloads/Iosevka-master/node_modules/libspiro-js/libspiro.js:218:22)
    at run_spiro (/home/meneldur/Downloads/Iosevka-master/node_modules/libspiro-js/libspiro.js:581:10)
    at Object.spiroToBezierOnContext (/home/meneldur/Downloads/Iosevka-master/node_modules/libspiro-js/libspiro.js:614:7)
    at _r0_t4._r76_t0 (/home/meneldur/Downloads/Iosevka-master/support/spirokit.js:313:185)
    at _r0_t4._r0_t17 (/home/meneldur/Downloads/Iosevka-master/support/glyph.js:79:100)
    at _r0_t4._r230_t2 (/home/meneldur/Downloads/Iosevka-master/buildglyphs.js:222:278)
    at _r102_t60 (/home/meneldur/Downloads/Iosevka-master/buildglyphs.js:122:171)
    at _r102_t79 (/home/meneldur/Downloads/Iosevka-master/buildglyphs.js:220:20)
    at _r0_t4._r102_t127 (/home/meneldur/Downloads/Iosevka-master/buildglyphs.js:515:423)
    at _r102_t60 (/home/meneldur/Downloads/Iosevka-master/buildglyphs.js:120:308)
onegroup.mk:43: recipe for target 'build/.pass0-iosevka-regular.fdt' failed
make[1]: *** [build/.pass0-iosevka-regular.fdt] Error 8
makefile:25: recipe for target 'fdts-default' failed
make: *** [fdts-default] Error 2
```

**Comment by be5invis** [comment]
Well installing `Math.hypot` globally cannot solve this problem. You can install it inside the repository and add this line at the beginning of `generate.js` (and maybe `extract.js`):
```js
require('es6-shim');
```
BTW, AFAIK the latest Node has built-in support for `Math.hypot`, as well as `Symbol.iterator`.

**Comment by ElSebita** [comment]
`core-js` was installed. Adding that line of code to `generate.js` and `extract-js` solved the problem.
Thanks!
