### ISSUE TITLE
error ELIFECYCLE on build (since Verda commit 73b05402)

### ISSUE THREAD

**Issue by sdothum** [be5invis/Iosevka#350]
* Your font version: git version 226210f0 Merge branch 'dev'
* Your font variant: custom
* Your operating system: Arch linux 5.2.8
* Your application using Iosevka: gvim, alacritty (term), vimb (browser)

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version: 11.15.0
* Your _otfcc_ version: 0.10.3
* Your `make` version: 4.2.1

npm run build -- ttf:iosevka-amphetype-mono output..
```
> iosevka@2.3.0 install /net/depot/Iosevka
> node checkenv

External dependency <otfccdump> is present.
External dependency <otfccbuild> is present.
External dependency <ttfautohint> is present.
npm WARN iosevka@2.3.0 No repository field.
npm WARN iosevka@2.3.0 No license field.

audited 943 packages in 1.502s
found 0 vulnerabilities


> iosevka@2.3.0 build /net/depot/Iosevka
> verda -f verdafile.js "ttf:iosevka-amphetype-mono"

● Note Invalidating build journal due to self-tracking.
Building process terminated.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@2.3.0 build: `verda -f verdafile.js "ttf:iosevka-amphetype-mono"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iosevka@2.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shum/.npm/_logs/2019-08-20T22_02_39_979Z-debug.log
```

* Your `parameters.toml`:
```
[verbose]
verbose = true

### Weights
[w-100]
stroke = 18
sb = 72
dotsize = 53
periodsize = 55

cthin = 0.9
cthinb = 0.9
vtipfine = 1
shoulderfine = 0.8
pbarpos = 0.5

[w-200]
stroke = 36
sb = 68
dotsize = 70
periodsize = 77

cthin = 0.75
cthinb = 0.75
vtipfine = 1
pbarpos = 0.5

[w-300]
stroke = 56
sb = 64
dotsize = 100
periodsize = 115

vtipfine = 0.9
pbarpos = 0.51

[w-400]
sb = 60            # Side bearing.
stroke = 72        # Stroke width of horizontal strokes.
dotsize = 125      # "Visual" size of dots in /i.
periodsize = 140   # "Visual" size of period.

[w-500]
sb = 57
stroke = 84
dotsize = 135
periodsize = 160
smooth = 200

[w-600]
sb = 54
stroke = 97
dotsize = 145
periodsize = 168
essx = 1.07

rbalance = 55
rbalance2 =
### Slantness
[s-italic]
isItalic = true
slantAngle = 10
jhook = 120

[s-oblique]
isOblique = true
slantAngle = 10
jhook = 120

### Slab variant
[slab]
slab = true
onebalance = 10
overshootx = -16
[slab.multiplies]
sb = 1.1

### Spacings
[term]
spacing = 0
disableLigation = true

# Term variant with ligations
[termlig]
spacing = 0

[type]
inherits = ["xx-type"]
spacing = 2

[cc]
inherits = ["xx-cc"]
spacing = 3

###### Widths
# NOTE: this section is highly experimental
# HANDLE WITH EXTREME CARE
# Expanded : I heard someone want it being wider...
[wd-expanded.multiplies]
width = 1.15
sb = 1.15
[expanded]
inherits = ['wd-expanded']

# Compressed : And someone else want it being narrower
[wd-compressed.multiplies]
width = 0.9
sb = 0.9
[compressed]
inherits = ['wd-compressed']

###### Full-width codes
[xx-type]
spacing = 2
[xx-type.appends]
fullwidth_codes = [
        164, #¤
        177, #±
        215, #×
        247, #÷
        711, #ˇ
        713, #ˉ
        8212, #—
        8214, #‖
        8251, #※
        8451, #℃
        8712, #∈
        8719, #∏
        8720,
        8721, #∑
        8733, #∝
        8734, #∞
        8736, #∠
        8741, #∥
        8743, #∧
        8744, #∨
        8745, #∩
        8746, #∪
        8747, #∫
        8750, #∮
        8756, #∴
        8757, #∵
        8758, #∶
        8759, #∷
        8765, #∽
        8776, #≈
        8780, #≌
        8800, #≠
        8801, #≡
        8804, #≤
        8805, #≥
        8814, #≮
        8815, #≯
        8816,8817,8834,8835,8836,8837,
        8853, #⊕
        8854,
        8857, #⊙
        8866,
        8867,
        8868,
        8869, #⊥
        8978, #⌒
        8896,8897,8898,8899
]

[xx-cc]
inherits = ["xx-type"]
spacing = 3
[xx-cc.appends]
fullwidth_codes = [
        167, #§
        8242, #′
        8243, #″
[ligset-swift]
defLigSet = "SWFT"

[ligset-purescript]
defLigSet = "PURS"

[ligset-coq]
defLigSet = "XV00"

###### Leading
[leading-750]
leading = 1719
[leading-1000]
leading = 1719
[leading-1250]
leading = 1719
[leading-1500]
leading = 1719
[leading-1750]
leading = 1719
[leading-2000]
leading = 1719

###### Powerline
[powerline-scale-y-750]
powerlineScaleY = 0.75
[powerline-scale-y-875]
powerlineScaleY = 0.875
[powerline-scale-y-1000]
powerlineScaleY = 1
[powerline-scale-y-1125]
powerlineScaleY = 1.125
[powerline-scale-y-1250]powerlineScaleY = 1.25
[powerline-scale-y-1375]
powerlineScaleY = 1.375
[powerline-scale-y-1500]
powerlineScaleY = 1.5
[powerline-scale-x-750]
powerlineScaleX = 0.75
[powerline-scale-x-875]
powerlineScaleX = 0.875
[powerline-scale-x-1000]
powerlineScaleX = 1
[powerline-scale-x-1125]
powerlineScaleX = 1.125
[powerline-scale-x-1250]
powerlineScaleX = 1.25
[powerline-scale-x-1375]
powerlineScaleX = 1.375
[powerline-scale-x-1500]
powerlineScaleX = 1.5
[powerline-shift-y-n500]
powerlineShiftY = -500
[powerline-shift-y-n450]
powerlineShiftY = -450
[powerline-shift-y-n400]
powerlineShiftY = -400
[po
[powerline-shift-y-p300]
powerlineShiftY = 300
[powerline-shift-y-p350]
powerlineShiftY = 350
[powerline-shift-y-p400]
powerlineShiftY = 400
[powerline-shift-y-p450]
powerlineShiftY = 450
[powerline-shift-y-p500]
powerlineShiftY = 500
[powerline-shift-x-n500]
powerlineShiftX = -500
[powerline-shift-x-n450]
powerlineShiftX = -450
[powerline-shift-x-n400]
powerlineShiftX = -400
[powerline-shift-x-n350]
powerlineShiftX = -350
[powerline-shift-x-n300]
powerlineShiftX = -300
[powerline-shift-x-n250]
powerlineShiftX = -250
[powerline-shift-x-n200]
powerlineShiftX = -200
[powerline-shift-x-n150]
powerlineShiftX = -150
[powerline-shift-x-n100]
powerlineShiftX = -100
[powerline-shift-x-n50]
powerlineShiftX = -50
[powerline-shift-x-0]
powerlineShiftX = 0
[powerline-shift-x-p50]
powerlineShiftX = 50
[powerline-shift-x-p100]
powerlineShiftX = 100
[powerline-shift-x-p150]
powerlineShiftX = 150
[powerline-shift-x-p200]
powerlineShiftX = 200
[powerline-shift-x-p250]
powerlineShiftX = 250
[powerline-shift-x-p300]
powerlineShiftX = 300
[powerline-shift-x-p350]
powerlineShiftX = 350
[powerline-shift-x-p400]
powerlineShiftX = 400
[powerline-shift-x-p450]
powerlineShiftX = 450
[powerline-shift-x-p500]
powerlineShiftX = 500

# Compatibility PUA ligature sample
# [[iosevka.compLig]]
# unicode = 57600 # 0xE100
# featureTag = 'XV00'
# sequence = '<*>'
```
npm log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   'ttf:iosevka-amphetype-mono' ]
2 info using npm@6.10.3
3 info using node@v11.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle iosevka@2.3.0~prebuild: iosevka@2.3.0
6 info lifecycle iosevka@2.3.0~build: iosevka@2.3.0
7 verbose lifecycle iosevka@2.3.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle iosevka@2.3.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/net/de
pot/Iosevka/node_modules/.bin:/home/shum/bin:/home/shum/bin/functions:/home/shum/bin/functions/config:/home/shum/bin/fun
ctions/conky:/home/shum/bin/functions/demo:/home/shum/bin/functions/dev:/home/shum/bin/functions/dmenu:/home/shum/bin/fu
nctions/edit:/home/shum/bin/functions/file:/home/shum/bin/functions/hardware:/home/shum/bin/functions/log:/home/shum/bin
/functions/mail:/home/shum/bin/functions/media:/home/shum/bin/functions/network:/home/shum/bin/functions/office:/home/sh
um/bin/functions/package:/home/shum/bin/functions/package/arch:/home/shum/bin/functions/package/void:/home/shum/bin/func
tions/process:/home/shum/bin/functions/query:/home/shum/bin/functions/regex:/home/shum/bin/functions/shell:/home/shum/bi
n/functions/sysadmin:/home/shum/bin/functions/test:/home/shum/bin/functions/ui:/home/shum/bin/functions/user:/home/shum/
bin/functions/web:/home/shum/.local/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/b
in/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/shum/.gem/ruby/2.6.3/bin:/home/shum/.cabal/bin:/bin:/sbin:/us
r/sbin:/usr/bin/core_perl:/usr/local/games
9 verbose lifecycle iosevka@2.3.0~build: CWD: /net/depot/Iosevka
10 silly lifecycle iosevka@2.3.0~build: Args: [ '-c', 'verda -f verdafile.js "ttf:iosevka-amphetype-mono"' ]
11 silly lifecycle iosevka@2.3.0~build: Returned: code: 1  signal: null
12 info lifecycle iosevka@2.3.0~build: Failed to exec build script
13 verbose stack Error: iosevka@2.3.0 build: `verda -f verdafile.js "ttf:iosevka-amphetype-mono"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:1
4)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid iosevka@2.3.0
15 verbose cwd /net/depot/Iosevka
16 verbose Linux 5.2.8-arch1-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--" "ttf:iosevka-amphetype-mono"
18 verbose node v11.15.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error iosevka@2.3.0 build: `verda -f verdafile.js "ttf:iosevka-amphetype-mono"`
22 error Exit status 1
23 error Failed at the iosevka@2.3.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by be5invis** [comment]
Use two columns like `ttf::iosevka-amphetype-mono` rather than `ttf:iosevka-amphetype-mono`. This is an intentional change and README should have shown this.

**Comment by sdothum** [comment]
Gah! Don't know how i could have missed that. i even read that correction in another issue thread.

Many apologies. And thank you for your patience and for creating the best mono font.
