### ISSUE TITLE
node-gyp errors compiling on Arch Linux

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#433]
* Your font version: `r1448.7ff1f95c`
* Your font variant: `fixed`
* Your operating system (name and version): Arch Linux

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: `13.10.0`
* Your _otfcc_ version: `0.10.3.alpha`
* Your `private-build-plans.toml`, if present:
```
# docs:
# https://github.com/be5invis/Iosevka
# https://github.com/be5invis/Iosevka/blob/master/private-build-plans.sample.toml
# https://github.com/be5invis/Iosevka#build-your-own-style

# ss## stylistic sets:
# https://raw.githubusercontent.com/be5invis/Iosevka/master/images/stylesets.png

# cv## character variants:
# https://raw.githubusercontent.com/be5invis/Iosevka/master/images/charvars.png

# ligset-* ligature sets:
# https://raw.githubusercontent.com/be5invis/Iosevka/master/images/ligations.png

[buildPlans.iosevka-custom]        # Plan name
family = "Iosevka Custom"          # Font menu family name
design = [                         # Common styles

  "cv05",                          # hooky i
  "cv14",                          # dotted 0
  "cv24",                          # open double story g
  "cv26",                          # short leg m
  "cv27",                          # tailed l
  "cv33",                          # short @
  "cv46",                          # flat top 3
  "cv53",                          # tailed f
  "cv54",                          # open short $
  "cv60",                          # hex *
  "cv69",                          # curly kK
  "cv72",                          # curly vV
  "cv74",                          # curly A
  "cv76",                          # curly wW
  "cv78",                          # curly xX
  "cv79",                          # curly y
  "cv81",                          # curly Y
  "cv83",                          # curly R

]
# upright = []                     # Upright-only styles
# italic = []                      # Italic-only styles
# oblique = []                     # Oblique-only styles

[buildPlans.iosevka-fixed-custom]  # Plan name
family = "Iosevka Fixed Custom"    # Font menu family name
design = [                         # Common styles

  "fixed",                         # strict mono; no ligatures

  "cv05",                          # hooky i
  "cv14",                          # dotted 0
  "cv24",                          # open double story g
  "cv26",                          # short leg m
  "cv27",                          # tailed l
  "cv33",                          # short @
  "cv46",                          # flat top 3
  "cv53",                          # tailed f
  "cv54",                          # open short $
  "cv60",                          # hex *
  "cv69",                          # curly kK
  "cv72",                          # curly vV
  "cv74",                          # curly A
  "cv76",                          # curly wW
  "cv78",                          # curly xX
  "cv79",                          # curly y
  "cv81",                          # curly Y
  "cv83",                          # curly R

]
# upright = []                     # Upright-only styles
# italic = []                      # Italic-only styles
# oblique = []                     # Oblique-only styles

[buildPlans.iosevka-term-custom]   # Plan name
family = "Iosevka Term Custom"     # Font menu family name
design = [                         # Common styles

  "term",                          # strict mono; with ligatures

  "cv05",                          # hooky i
  "cv14",                          # dotted 0
  "cv24",                          # open double story g
  "cv26",                          # short leg m
  "cv27",                          # tailed l
  "cv33",                          # short @
  "cv46",                          # flat top 3
  "cv53",                          # tailed f
  "cv54",                          # open short $
  "cv60",                          # hex *
  "cv69",                          # curly kK
  "cv72",                          # curly vV
  "cv74",                          # curly A
  "cv76",                          # curly wW
  "cv78",                          # curly xX
  "cv79",                          # curly y
  "cv81",                          # curly Y
  "cv83",                          # curly R

]
# upright = []                     # Upright-only styles
# italic = []                      # Italic-only styles
# oblique = []                     # Oblique-only styles
```
* The detailed error log:
The builds do seem to work, but they always start this way:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> ttf2woff2@2.0.3 install /home/andy/Code/aur/ttf-iosevka-fixed-custom-git/src/Iosevka/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE convert(Nan::NAN_METHOD_ARGS_TYPE)’:
../csrc/addon.cc:10:49: error: no matching function for call to ‘v8::Value::ToObject()’
   10 |   Local<Object> inputBuffer = info[0]->ToObject();
      |                                                 ^
In file included from /home/andy/.cache/node-gyp/13.10.0/include/node/node.h:67,
                 from ../../nan/nan.h:54,
                 from ../csrc/addon.cc:1:
/home/andy/.cache/node-gyp/13.10.0/include/node/v8.h:2754:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
 2754 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
      |                                            ^~~~~~~~
/home/andy/.cache/node-gyp/13.10.0/include/node/v8.h:2754:44: note:   candidate expects 1 argument, 0 provided
make: *** [addon.target.mk:133: Release/obj.target/addon/csrc/addon.o] Error 1
make: *** Waiting for unfinished jobs....
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.5.7-zen1-1-zen
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/andy/Code/aur/ttf-iosevka-fixed-custom-git/src/Iosevka/node_modules/ttf2woff2
gyp ERR! node -v v13.10.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

> ejs@3.0.1 postinstall /home/andy/Code/aur/ttf-iosevka-fixed-custom-git/src/Iosevka/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> iosevka@3.0.0-rc.1 install /home/andy/Code/aur/ttf-iosevka-fixed-custom-git/src/Iosevka
> node checkenv

External dependency <otfccdump> is present.
External dependency <otfccbuild> is present.
External dependency <ttfautohint> is present.
External dependency <otf2otc> is present.
npm WARN iosevka@3.0.0-rc.1 No repository field.
npm WARN iosevka@3.0.0-rc.1 No license field.

added 391 packages from 360 contributors and audited 875 packages in 11.779s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> iosevka@3.0.0-rc.1 build /home/andy/Code/aur/ttf-iosevka-fixed-custom-git/src/Iosevka
> verda -f verdafile.js "ttf::iosevka-fixed-custom"

● Note Invalidating build journal due to self-tracking.
```
And `node_modules/ttf2woff2/builderror.log`:
```
make: Entering directory '/home/andy/Code/aur/ttf-iosevka-fixed-custom-git/src/Iosevka/node_modules/ttf2woff2/build'
  CXX(target) Release/obj.target/addon/csrc/addon.o
  CXX(target) Release/obj.target/addon/csrc/woff2/glyph.o
  CXX(target) Release/obj.target/addon/csrc/woff2/font.o
  CXX(target) Release/obj.target/addon/csrc/woff2/normalize.o
  CXX(target) Release/obj.target/addon/csrc/woff2/table_tags.o
  CXX(target) Release/obj.target/addon/csrc/woff2/transform.o
  CXX(target) Release/obj.target/addon/csrc/woff2/variable_length.o
  CXX(target) Release/obj.target/addon/csrc/woff2/woff2_common.o
  CXX(target) Release/obj.target/addon/csrc/woff2/woff2_enc.o
  CXX(target) Release/obj.target/addon/csrc/enc/backward_references.o
  CXX(target) Release/obj.target/addon/csrc/enc/block_splitter.o
  CXX(target) Release/obj.target/addon/csrc/enc/brotli_bit_stream.o
make: Leaving directory '/home/andy/Code/aur/ttf-iosevka-fixed-custom-git/src/Iosevka/node_modules/ttf2woff2/build'
```
---
I am building with:

```bash
npm install
npm update
npm run build -- ttf::iosevka-fixed-custom
```

If there's a more detailed error log somewhere, or other information I can provide, please let me know.

**Comment by be5invis** [comment]
Looks like an error when installing `ttf2woff2`.
Please report to here: https://github.com/nfroidure/ttf2woff2/issues

**Comment by AndydeCleyre** [comment]
Well, is there any real reason Iosevka requires the `ttf2woff2` release from five years ago? Can it use the release from 2019 instead? That installs no problem, and I wouldn't expect a five year old release to build perfectly.

**Comment by be5invis** [comment]
Updated in dev.
