### ISSUE TITLE
Does Iosevka requires specific version of node.js?

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#46]
Sorry, I have no experience with node.js. I am trying to build Iosevka, `make` fails with error:

    $ make
    make[1]: Entering directory '/home/vdb/tmp/Iosevka'
        Start build font Iosevka Thin 1.5.5 (Elvirel)

    /home/vdb/tmp/Iosevka/node_modules/libspiro-js/libspiro.js:218
            r[i].seg_ch = Math.hypot(dx, dy);
                               ^
    TypeError: Object #<Object> has no method 'hypot'
        at setup_path (/home/vdb/tmp/Iosevka/node_modules/libspiro-js/libspiro.js:218:28)
        at run_spiro (/home/vdb/tmp/Iosevka/node_modules/libspiro-js/libspiro.js:581:13)
        at Object.spiroToBezierOnContext (/home/vdb/tmp/Iosevka/node_modules/libspiro-js/libspiro.js:614:13)
        at _r0_t5._r79_t0 (/home/vdb/tmp/Iosevka/support/spirokit.js:316:241)
        at _r0_t5._r0_t18 (/home/vdb/tmp/Iosevka/support/glyph.js:71:151)
        at _r0_t5._r236_t2 (/home/vdb/tmp/Iosevka/buildglyphs.js:707:31)
        at _r105_t171 (/home/vdb/tmp/Iosevka/buildglyphs.js:370:26)
        at _r105_t191 (/home/vdb/tmp/Iosevka/buildglyphs.js:700:16)
        at _r0_t5._r432_t0 (/home/vdb/tmp/Iosevka/buildglyphs.js:1434:39)
        at _r105_t171 (/home/vdb/tmp/Iosevka/buildglyphs.js:361:26)
    onegroup.mk:49: recipe for target 'build/.pass0-iosevka-thin.fdt' failed
    make[1]: *** [build/.pass0-iosevka-thin.fdt] Error 8
    make[1]: Leaving directory '/home/vdb/tmp/Iosevka'
    makefile:26: recipe for target 'fonts-default' failed
    make: *** [fonts-default] Error 2

I have found a [page](https://stackoverflow.com/questions/28388885/ecmascript-6-features-available-in-node-js-0-12) which says `Math.hypot` function was added to `node.js` version 0.12, while my system has `node.js` 0.10.36. 

Is that correct? If so, please update `README.md` and document this requirement.

**Comment by be5invis** [comment]
See #31, install `core-js` package and add a `require(core-js)` at the beginning of `generator.js`.
The version requirement is added to `README.md` either.
Closed.

**Comment by van-de-bugger** [comment]
Thanks, this works.
