### ISSUE TITLE
Building iosevka-custom with "no-cv-ss" failed since commit 866dc4d on dev branch

### ISSUE THREAD

**Issue by cwchien** [be5invis/Iosevka#460]
* Your font version: git since 866dc4d (dev branch)
* Your operating system (name and version): Ubuntu Linux 19.10

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 12.16.1
* Your _otfcc_ version: v0.10.3-alpha
* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-custom]                                 # <iosevka-custom> is your plan name
family = "Iosevka Fixed"                                    # Font menu family name
design = ["sp-fixed", "no-cv-ss", "ss14", "v-k-straight", "v-capital-g-toothless",
          "v-zero-slashed", "v-seven-serifed", "v-asterisk-high", "v-dollar-open", "v-numbersign-slanted"]  # JetBrains Mono Style

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-custom.slants]
upright = "normal"
italic = "italic"
```
* The detailed error log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/cwchien/.nvm/versions/node/v12.16.1/bin/node',
1 verbose cli   '/home/cwchien/.nvm/versions/node/v12.16.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   'ttf::iosevka-custom'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle iosevka@3.0.0-rc.4~prebuild: iosevka@3.0.0-rc.4
6 info lifecycle iosevka@3.0.0-rc.4~build: iosevka@3.0.0-rc.4
7 verbose lifecycle iosevka@3.0.0-rc.4~build: unsafe-perm in lifecycle true
8 verbose lifecycle iosevka@3.0.0-rc.4~build: PATH: /home/cwchien/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:...
9 verbose lifecycle iosevka@3.0.0-rc.4~build: CWD: /home/cwchien/.GitRepos/Remote/Iosevka
10 silly lifecycle iosevka@3.0.0-rc.4~build: Args: [ '-c', 'verda -f verdafile.js "ttf::iosevka-custom"' ]
11 silly lifecycle iosevka@3.0.0-rc.4~build: Returned: code: 1  signal: null
12 info lifecycle iosevka@3.0.0-rc.4~build: Failed to exec build script
13 verbose stack Error: iosevka@3.0.0-rc.4 build: `verda -f verdafile.js "ttf::iosevka-custom"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/cwchien/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/cwchien/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid iosevka@3.0.0-rc.4
15 verbose cwd /home/cwchien/.GitRepos/Remote/Iosevka
16 verbose Linux 5.3.0-42-generic
17 verbose argv "/home/cwchien/.nvm/versions/node/v12.16.1/bin/node" "/home/cwchien/.nvm/versions/node/v12.16.1/bin/npm" "run" "build" "ttf::iosevka-custom"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error iosevka@3.0.0-rc.4 build: `verda -f verdafile.js "ttf::iosevka-custom"`
22 error Exit status 1
23 error Failed at the iosevka@3.0.0-rc.4 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
---
I build my iosevka-custom on dev branch to get newest version.
Everything is fine, but since 866dc4d, the building always fails if I added "no-cv-ss".
(build passed if removing it)

Thanks.

**Comment by cwchien** [comment]
Confirm fixed. Thanks.
