### ISSUE TITLE
`SyntaxError: Unexpected token {` when building

### ISSUE THREAD

**Issue by A-Manning** [be5invis/Iosevka#486]
* Your font version: (Release or git, version)
Git, `eaa6443`
* Your font variant:
Custom
* Your operating system (name and version):
Ubuntu 19.10
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
N/A
If you have problem when building Iosevka, please provide these information:

* Your Node.js version:
v8.9.4
* Your _otfcc_ version:
Git, `56fc731`
* Your `parameters.toml`, paste if modified:
N/A
* Your `build-plans.toml`, paste if modified:
N/A
* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
design = [
'extended',
'calt-center-ops',
'calt-arrow',
'calt-arrow2',
'calt-trig',
'calt-eqeq',
'calt-eqeqeq',
'calt-ineq',
'calt-ltgt-diamond',
'calt-brst',
'calt-logic',
'calt-llgg',
'calt-dotoper',
'calt-html-comment',
'v-i-italic',
'v-l-italic',
'v-zero-dotted',
'v-paragraph-low',
'v-g-opendoublestorey',
'v-at-fourfold',
'v-dollar-open',
'v-numbersign-slanted',
'v-one-base',
'v-asterisk-hexlow',
'v-lig-ltgteq-slanted',
'v-lambda-curly',
'v-nine-turned-six'
]
```
* The detailed error log:
```

> iosevka@3.0.0-rc.6 build /home/ash/Programs/iosevka
> verda -f verdafile.js "contents::iosevka"

/home/ash/Programs/iosevka/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ash/Programs/iosevka/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@3.0.0-rc.6 build: `verda -f verdafile.js "contents::iosevka"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iosevka@3.0.0-rc.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ash/.npm/_logs/2020-04-09T16_35_35_616Z-debug.log
```

'Complete log':
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ash/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/ash/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   'contents::iosevka' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle iosevka@3.0.0-rc.6~prebuild: iosevka@3.0.0-rc.6
6 info lifecycle iosevka@3.0.0-rc.6~build: iosevka@3.0.0-rc.6
7 verbose lifecycle iosevka@3.0.0-rc.6~build: unsafe-perm in lifecycle true
8 verbose lifecycle iosevka@3.0.0-rc.6~build: PATH: /home/ash/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ash/Programs/iosevka/node_modules/.bin:/home/ash/.opam/4.07.0/bin:/home/ash/.nvm/versions/node/v8.9.4/bin:/home/ash/.cargo/bin:/home/ash/.cabal/bin:/home/ash/.local/bin:/home/ash/.cargo/bin:/home/ash/.opam/4.07.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ash/.dotnet/tools:/home/ash/Programs/z3/bin:../otfcc/bin/release-x64/
9 verbose lifecycle iosevka@3.0.0-rc.6~build: CWD: /home/ash/Programs/iosevka
10 silly lifecycle iosevka@3.0.0-rc.6~build: Args: [ '-c', 'verda -f verdafile.js "contents::iosevka"' ]
11 silly lifecycle iosevka@3.0.0-rc.6~build: Returned: code: 1  signal: null
12 info lifecycle iosevka@3.0.0-rc.6~build: Failed to exec build script
13 verbose stack Error: iosevka@3.0.0-rc.6 build: `verda -f verdafile.js "contents::iosevka"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ash/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/ash/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid iosevka@3.0.0-rc.6
15 verbose cwd /home/ash/Programs/iosevka
16 verbose Linux 5.3.0-45-generic
17 verbose argv "/home/ash/.nvm/versions/node/v8.9.4/bin/node" "/home/ash/.nvm/versions/node/v8.9.4/bin/npm" "run" "build" "--" "contents::iosevka"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error iosevka@3.0.0-rc.6 build: `verda -f verdafile.js "contents::iosevka"`
22 error Exit status 1
23 error Failed at the iosevka@3.0.0-rc.6 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by be5invis** [comment]
Seems a dependency `fs-extra` used a later JS syntax that Node 8.x doesn't support.
Upgrading to Node 12 will fix this.
I'll update the docs.
Closed.
