### ISSUE TITLE
Build fails on Fedora 22 and 23.

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#61]
Hi,

I am building iosevka for Fedora. 1.7.3 was built successfully on F22, F23 and rawhide (future F24). However, 1.7.4 fails on F22 and F23. The first error is:

    node ./node_modules/patel/bin/patel-c --optimize --strict support/glyph.ptl -o support/glyph.js
    ReferenceError: Symbol is not defined
        at _r85_t0 (eval at _r118_t38 (./node_modules/patel/active/externs.js:1135:28), <anonymous>:1346:37)
        at _r203_t10 (./node_modules/patel/active/externs.js:1150:34)
        at _r1_t13 (./node_modules/patel/active/ex.js:223:52)
        at _r119_t2 (./node_modules/patel/active/ex.js:28:97)
        at _r1_t13 (./node_modules/patel/active/ex.js:133:60)
        at _r119_t2 (./node_modules/patel/active/ex.js:28:97)
        at _r1_t13 (./node_modules/patel/active/ex.js:118:38)
        at _r119_t2 (./node_modules/patel/active/ex.js:28:97)
        at _r118_t18 (./node_modules/patel/active/externs.js:390:21)
        at _r118_t19 (./node_modules/patel/active/externs.js:435:16)

Since build completes successfully on rawhide I guess F22/23 has old version of some required tool, may be nodejs? F23 has node v0.10.36, and patch described in #31.

Do you have any idea what the problem is? Is there any workaround?

**Comment by be5invis** [comment]
`Symbol` is a ES6 built-in function, and the older version of Node may not support it.
So yes, upgrading Node to 5.x will solve this.
