### ISSUE TITLE
Build error with commit d0f37b5464e8b3f47e57d9dbb491e03df8ce3199 in dev branch

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#653]
This morning I pulled the latest commits and tried to build my own fonts and got this error:
`
Error: Error: Cannot find glyph 'rflap.top-serifed'
`

I've attached the full error log below ...

---

* Your font version: d0f37b5464e8b3f47e57d9dbb491e03df8ce3199
* Your font variant: custom build
* Your operating system (name and version): Linux Gentoo ~amd64
* Your application using Iosevka: kitty, awesomewm, gtk+

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: v14.6.0
* Your _otfcc_ version: 0.10.4
* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-artesanal-curly]
family = "Iosevka Artesanal Curly"
design = [
  "slab",
  "v-a-doublestorey-tailed",
  "v-f-straight-tailed",
  "v-g-opendoublestorey",
  "v-i-italic",
  "v-k-curly",
  "v-l-italic",
  "v-m-shortleg",
  "v-capital-q-crossing",
  "v-r-top-serifed",
  "v-eszet-traditional",
  "v-u-tailed",
  "v-v-curly",
  "v-w-curly",
  "v-x-curly",
  "v-y-curly",
  "v-capital-y-curly",
  "v-z-with-horizontal-crossbar",
  "v-capital-z-with-horizontal-crossbar",
  "v-zero-reverse-slashed",
  "v-three-flattop",
  "v-four-semi-open",
  "v-six-open-contour",
  "v-seven-crossbar-serifed",
  "v-nine-open-contour",
  "v-ampersand-flat-top",
  "v-bar-force-upright",
  "v-tilde-high",
  "v-asterisk-high",
  "v-paragraph-high",
  "v-caret-high"
]
[buildPlans.iosevka-artesanal-curly.widths.normal]
shape = 500
menu  = 5
css   = "normal"
[buildPlans.iosevka-artesanal-curly.weights.regular]
shape = 400
menu  = 400
css   = 400
[buildPlans.iosevka-artesanal-curly.weights.semibold]
shape = 600
menu  = 600
css   = 600
[buildPlans.iosevka-artesanal-curly.weights.bold]
shape = 660
menu  = 700
css   = 700
[buildPlans.iosevka-artesanal-curly.weights.heavy]
shape = 900
menu  = 900
css   = 900
[buildPlans.iosevka-artesanal-curly.slopes]
upright = "normal"
italic = "italic"
```
* The detailed error log:
```
> iosevka@3.3.1 build /usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git
> verda -f verdafile.js "ttf::iosevka-artesanal-curly"

<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
<Failure> Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)

Error: Error: Cannot find glyph 'rflap.top-serifed'
    at Glyph._r296_t2 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:399:23)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at Glyph._r273_t8 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:348:31)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:57:14)
    at _r265_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:141:26)
    at _r263_t11 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/common-shapes.js:345:16)
    at _r1_t37 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:6022:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:226:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
    at ChildProcess.<anonymous> (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/node_modules/verda/lib/actions/nodejs/command.js:55:31)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@3.3.1 build: `verda -f verdafile.js "ttf::iosevka-artesanal-curly"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iosevka@3.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/swimmer/.npm/_logs/2020-07-30T08_43_11_166Z-debug.log
```

**Comment by be5invis** [comment]
Fixed.

**Comment by wimstefan** [comment]
Many thanks for the lightning fast response!
