### ISSUE TITLE
Building with private-build-plans.toml fails for 3.4.2

### ISSUE THREAD

**Issue by dixius99** [be5invis/Iosevka#667]
If I try to build with `private-build-plans.toml` for 3.4.2, even when using the contents of the sample file with no changes, I get errors and the build fails. Using the exact process works fine for 3.4.1 and previous versions.

I get a few different, but similar, errors during the build process Here are 2 examples:

```
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-extendedboldoblique.raw.ttf":
 Error: TypeError: Glyph::unicode has been deprecated
    at Glyph.set unicode [as unicode] (/Users/michael/Downloads/Iosevka-3.4.2/font-src/support/glyph.js:26:9)
    at /Users/michael/Downloads/Iosevka-3.4.2/font-src/otl/compat-ligature.js:157:29
    at _r1_t11 (/Users/michael/Downloads/Iosevka-3.4.2/font-src/otl/compat-ligature.js:172:10)
    at _r1_t20 (/Users/michael/Downloads/Iosevka-3.4.2/font-src/otl/index.js:88:9)
    at module.exports (/Users/michael/Downloads/Iosevka-3.4.2/font-src/gen/build-font.js:18:14)
    at main (/Users/michael/Downloads/Iosevka-3.4.2/font-src/index.js:15:31)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-3.4.2/node_modules/verda/lib/actions/nodejs/command.js:55:31)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
and
```
Building process terminated.
Error: TypeError: Glyph::unicode has been deprecated
    at Glyph.set unicode [as unicode] (/Users/michael/Downloads/Iosevka-3.4.2/font-src/support/glyph.js:26:9)
    at /Users/michael/Downloads/Iosevka-3.4.2/font-src/otl/compat-ligature.js:157:29
    at _r1_t11 (/Users/michael/Downloads/Iosevka-3.4.2/font-src/otl/compat-ligature.js:172:10)
    at _r1_t20 (/Users/michael/Downloads/Iosevka-3.4.2/font-src/otl/index.js:88:9)
    at module.exports (/Users/michael/Downloads/Iosevka-3.4.2/font-src/gen/build-font.js:18:14)
    at main (/Users/michael/Downloads/Iosevka-3.4.2/font-src/index.js:15:31)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-3.4.2/node_modules/verda/lib/actions/nodejs/command.js:55:31)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

---

* Your font version: (3.4.2)
* Your font variant: `private-build-plans.toml`
* Your operating system (macOS 10.15.6):
* Your application using Iosevka: N/A

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 14.8.0
* Your _otfcc_ version: 0.10.4
* Your `params/parameters.toml`, paste if modified: no changes
* Your `build-plans.toml`, paste if modified: no changes
* Your `private-build-plans.toml`, if present: no changes
* The detailed error log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/14.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   'contents::iosevka-custom'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v14.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle iosevka@3.4.2~prebuild: iosevka@3.4.2
6 info lifecycle iosevka@3.4.2~build: iosevka@3.4.2
7 verbose lifecycle iosevka@3.4.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle iosevka@3.4.2~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/michael/Downloads/Iosevka-3.4.2/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/sbin:/usr/local/scripts
9 verbose lifecycle iosevka@3.4.2~build: CWD: /Users/michael/Downloads/Iosevka-3.4.2
10 silly lifecycle iosevka@3.4.2~build: Args: [ '-c', 'verda -f verdafile.js "contents::iosevka-custom"' ]
11 silly lifecycle iosevka@3.4.2~build: Returned: code: 1  signal: null
12 info lifecycle iosevka@3.4.2~build: Failed to exec build script
13 verbose stack Error: iosevka@3.4.2 build: `verda -f verdafile.js "contents::iosevka-custom"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid iosevka@3.4.2
15 verbose cwd /Users/michael/Downloads/Iosevka-3.4.2
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/Cellar/node/14.8.0/bin/node" "/usr/local/bin/npm" "run" "build" "--" "contents::iosevka-custom"
18 verbose node v14.8.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 1
22 error iosevka@3.4.2 build: `verda -f verdafile.js "contents::iosevka-custom"`
22 error Exit status 1
23 error Failed at the iosevka@3.4.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by clsn** [comment]
I have the same problem, using  the container setup from https://github.com/ejuarezg/containers.git

**Comment by adamkiss** [comment]
I think it might be related to the fact that it's node 14 - when I tried the container setup, I've had the same errors, on the latest node 12 I don't.

**Comment by be5invis** [comment]
Should be related with compat-ligature (a feature that is rarely used...)

**Comment by dixius99** [comment]
So, if I remove that section from `private-build-plans.toml`, it should work? I'll try later tonight.

**Comment by be5invis** [comment]
@dixius99 Could you please provide your `private-build-plans.toml` so I could investigate?

**Comment by be5invis** [comment]
@dixius99 Just commited a fix. You can try the latest `dev` to see whether it is fixed.

**Comment by dixius99** [comment]
Fixed for me 🙂

**Comment by be5invis** [comment]
Closed as fixed.
