### ISSUE TITLE
Both v-l-serifed-asymmetric and v-capital-j-serifed-both-sides share the same code

### ISSUE THREAD

**Issue by adamkiss** [be5invis/Iosevka#668]
I've been trying to build my own Iosevka with symmetric J and build kept failing with "Error: Cannot find glyph 'ldot.serifedAsymmetric'", which was weird, because I haven't used that one.

But I was using shortcodes for characters instead of `v-letter-variation`, and I noticed that two characters use the same shortcode.

Quoting from the readme:

- v-l-serifed-asymmetric, VXDA: Serifed l with shorter top serif.
- v-capital-j-serifed-both-sides, VXDA: J with symmetric at both sides.

So>
- two characters share the same shortcode
- one is possibly failing

---

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: Node.js v12.18.3
* Your _otfcc_ version: 0.10.4
* Your `build-plans.toml`, paste if modified: unchanged
* Your `private-build-plans.toml`, if present:

[My font variant on Github](https://github.com/adamkiss/iosevka-ak2/blob/master/private-build-plans.toml)
<details>
<summary>Or included here</summary>

```toml
[buildPlans.iosevka-ak2]
family = "Iosevka AK2"
design = [
    "cv01", # a (default)
    "VXBM", # b rounded bottom
    "VXBP", # d rounded bottom
    "cv84", # f serifed
    "cv11", # g default
    "VXCB", # h default
    "cv06", # i asymmtetric serif
    "cv58", # j rounded
    "cv68", # k default
    "cv10", # l z shaped
    # "VXDA", # l asymmetric serif
    "cv26", # m with shorter middle leg
    "VXCF", # n default
    "VXCR", # p rounded top,
    "VXCS", # 1 rounded top
    "cv86", # r serif
    "VXDC", # t sharp bottom
    "cv79", # y curly
    "VXBD", # z default
    "cv73", # A default,
    "VXAQ", # B rounded
    "VXBG", # D default
    "cv92", # G rounded bottom
    "v-capital-j-serifed-both-sides", # J serif asymmetric?
    "VXCI", # M default
    "VXCA", # Q rounded bottom
    "cv82", # R default
    "cv81", # Y curly
    "cv13", # 0 slash
    "cv51", # 1 serif
    "cv46", # 3 sharp
    "VXAV", # 4 like calculator
    "VXAE", # 6 rounded bottom
    "VXAX", # 7 with cross over
    "cv96", # 9 rounded
    "cv17", # ~ middle
    "cv61", # * middle with 6 legs
    "cv30", # ^ middle
    "VXAO", # ( ROUNDED
    "cv37", # { middle
    "VXBJ", # # slanted with space
    "VXAI", # & rounded
    "cv32", # @ nice
    "cv54", # $ dollar small,
    "cv63", # % default?
    "cv67", # <= ligature"
]
# overload…
italic = [
    "VXBU", # a curly
    "cv53", # f curly
    "cv24", # g curly
    "VXCC", # h curly serif
    "cv04", # i curly asymmetric
    "VXDE", # j curly asymmetric
    "cv08", # l curly asymmetric serif
    "VXCT", # q curly rounded top
    "cv40", # t curly bottom
    "cv72", # v curly bottom
    "cv78", # x curly bottom
    "VXBF", # y "curly" bottom
    "cv74", # A curly
    "VXBI", # J simplest
    "cv83", # R curly
    "cv65", # 7 simpler
    "VXBI", # # straight with space
    "VXAL", # & weird
]

[buildPlans.iosevka-ak2.slopes]
upright = "normal"
italic = "italic"
# skip oblique
```
</details>

* The detailed error log:

```
<Failure> Error: Cannot find glyph 'ldot.serifedAsymmetric'
    at Glyph._r286_t2 (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/glyphs/common-derivatives.js:302:23)
    at Glyph.include (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/support/glyph.js:60:14)
    at Glyph._r271_t8 (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/glyphs/common-derivatives.js:277:31)
    at Glyph.include (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/support/glyph.js:60:14)
    at _r262_t9 (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/gen/build-glyphs.js:129:26)
    at _r260_t12 (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/glyphs/common-derivatives.js:274:16)
    at _r1_t22 (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/glyphs/letter-latin.js:1598:5)
    at Object._r1_t13 (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/glyphs/letter-latin.js:28:54)
    at _r1_t15 (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/gen/build-glyphs.js:210:48)
    at module.exports (/Users/runner/work/iosevka-ak2/iosevka-ak2/Iosevka/font-src/gen/build-font.js:13:13)
```
can be (probably) seen here: https://github.com/adamkiss/iosevka-ak2/runs/991311017?check_suite_focus=true#step:6:9

**Comment by be5invis** [comment]
Renamed the `l` variant tag to `VXDL`. Closed.

**Comment by adamkiss** [comment]
@be5invis Thank you. And thank you for the Iosevka font
