### ISSUE TITLE
private builds with 'curly' parameter crash with `TypeError: Cannot read property 'isMarkSet' of undefined`

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#671]
I build several different font variations out from the git sources and the one with `[design = "slab"]` is crashing with the error message above. The whole log file is attached below. Please let me know if you need anything else.

---

* Your font version: commit 138e29def272859595630db7a65676e2d0534ff7 (HEAD -> dev, origin/dev)
* Your font variant: Own build
* Your operating system (name and version): Gentoo Linux ~amd64
* Your application using Iosevka: everything on my machines :)

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: v14.8.0
* Your _otfcc_ version: version 0.10.4
* Your `params/parameters.toml`, paste if modified:
* Your `build-plans.toml`, paste if modified:
* Your `private-build-plans.toml`, if present:
```toml
[buildPlans.iosevka-artesanal-curly]
family = "Iosevka Artesanal Curly"
design = [
  "slab",
  "v-a-doublestorey-tailed",
  "v-f-straight-tailed",
  "v-g-opendoublestorey",
  "v-i-italic",
  "v-k-curly",
  "v-l-italic",
  "v-m-shortleg",
  "v-r-top-serifed",
  "v-eszet-traditional",
  "v-u-tailed",
  "v-v-curly",
  "v-w-curly",
  "v-x-curly",
  "v-y-curly",
  "v-capital-y-curly",
  "v-z-with-horizontal-crossbar",
  "v-capital-z-with-horizontal-crossbar",
  "v-zero-reverse-slashed",
  "v-three-flattop",
  "v-four-semi-open",
  "v-six-open-contour",
  "v-seven-crossbar-serifed",
  "v-nine-open-contour",
  "v-ampersand-flat-top",
  "v-bar-force-upright",
  "v-tilde-high",
  "v-asterisk-high",
  "v-paragraph-high",
  "v-caret-high"
]
[buildPlans.iosevka-artesanal-curly.widths.normal]
shape = 500
menu  = 5
css   = "normal"
[buildPlans.iosevka-artesanal-curly.weights.regular]
shape = 400
menu  = 400
css   = 400
[buildPlans.iosevka-artesanal-curly.weights.semibold]
shape = 600
menu  = 600
css   = 600
[buildPlans.iosevka-artesanal-curly.weights.bold]
shape = 660
menu  = 700
css   = 700
[buildPlans.iosevka-artesanal-curly.weights.heavy]
shape = 900
menu  = 900
css   = 900
[buildPlans.iosevka-artesanal-curly.slopes]
upright = "normal"
italic = "italic"
```
* The detailed error log:
```
> iosevka@3.4.3 build /usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git
> verda -f verdafile.js "ttf::iosevka-artesanal-curly"

<Failure> TypeError: Cannot read property 'isMarkSet' of undefined
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:65:24)
    at Glyph._r3231_t18 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7898:32)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:60:14)
    at _r262_t9 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:129:26)
    at _r1_t46 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7888:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:29:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:210:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
    at main (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/index.js:15:31)
<Failure> TypeError: Cannot read property 'isMarkSet' of undefined
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:65:24)
    at Glyph._r3231_t18 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7898:32)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:60:14)
    at _r262_t9 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:129:26)
    at _r1_t46 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7888:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:29:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:210:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
    at main (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/index.js:15:31)
<Failure> TypeError: Cannot read property 'isMarkSet' of undefined
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:65:24)
    at Glyph._r3231_t18 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7898:32)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:60:14)
    at _r262_t9 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:129:26)
    at _r1_t46 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7888:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:29:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:210:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
    at main (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/index.js:15:31)
<Failure> TypeError: Cannot read property 'isMarkSet' of undefined
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:65:24)
    at Glyph._r3231_t18 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7898:32)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:60:14)
    at _r262_t9 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:129:26)
    at _r1_t46 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7888:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:29:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:210:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
    at main (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/index.js:15:31)

Error: TypeError: Cannot read property 'isMarkSet' of undefined
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:65:24)
    at Glyph._r3231_t18 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7898:32)
    at Glyph.include (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/glyph.js:60:14)
    at _r262_t9 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:129:26)
    at _r1_t46 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:7888:5)
    at Object._r1_t13 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/glyphs/letter/latin.js:29:54)
    at _r1_t15 (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-glyphs.js:210:48)
    at module.exports (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/gen/build-font.js:13:13)
    at main (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/index.js:15:31)
    at ChildProcess.<anonymous> (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/node_modules/verda/lib/actions/nodejs/command.js:55:31)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@3.4.3 build: `verda -f verdafile.js "ttf::iosevka-artesanal-curly"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iosevka@3.4.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/swimmer/.npm/_logs/2020-08-20T08_17_58_167Z-debug.log
```

Your template doesn't work btw ;-) I always have to delete the spaces in front of the backticks to make the code shown with the correct format.

**Comment by wimstefan** [comment]
It works of course :)
Thank you so much for the incredibly fast response!!! 🙏
