### ISSUE TITLE
"Error: write EPIPE" at otfccBuild (font-src/index.js:105:12)

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#696]
I fail to build the current (at the moment) Iosevka `dev` branch (commit 53a20618e19582045e2151152d9db7dfb3f03008).

It seems the issue appeared in 54c5cc6be01692bc955516dd70fd16f275da7194 ("Make the build script directly output TTF"), related to how `child_process.spawn` interacts with `otfccbuild` binary at lowlevel and _not_ related to Iosevka build scripts themselves. Since I use a hand-built versions of `nodejs` and `otfcc`, I'd like to understand whether it's my fault building them from source or not.

Could you please provide _your_ environment where you succeeded building Iosevka `dev` branch? Distro name and version, glibc version, nodejs version and repository it came from, otfcc version?

Just in case, I provided the detailed information below. Note "Error Build cancelled by user" at build log since I pressed Ctrl+C after a few errors.

---

* Your font version: `dev` branch, commit 53a20618e19582045e2151152d9db7dfb3f03008
* Your operating system (name and version): Slackware-14.2, glibc-2.23

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: tried 10.21.0, 12.18.2, 14.5.0
* Your _otfcc_ version: tried 0.9.6, 0.10.4
* The detailed error log:
```
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-thin.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-thin.charmap","name":"iosevka-custom-thin","preHives":...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-thinoblique.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-thinoblique.charmap","name":"iosevka-custom-thi...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-thinitalic.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-thinitalic.charmap","name":"iosevka-custom-thini...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-extralight.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-extralight.charmap","name":"iosevka-custom-extra...
⠉⠩ Complete 096 - Executing 4 - Pending 164 (36%) ███████▒▒▒▒▒▒▒▒▒▒▒▒▒ | CPU:100% ██████████ - RAM:094% █████████▒<Failure> Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:105:12
    at new Promise (<anonymous>)
    at otfccBuild (/home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:92:9) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-thin.raw.ttf":
 Error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:105:12
    at new Promise (<anonymous>)
    at otfccBuild (/home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:92:9) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
    at ChildProcess.<anonymous> (/home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/node_modules/verda/lib/actions/nodejs/command.js:55:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-extralightoblique.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-extralightoblique.charmap","name":"iosevk...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-extralightitalic.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-extralightitalic.charmap","name":"iosevka-...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-light.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-light.charmap","name":"iosevka-custom-light","preHive...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-lightoblique.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-lightoblique.charmap","name":"iosevka-custom-l...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-lightitalic.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-lightitalic.charmap","name":"iosevka-custom-lig...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-regular.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-regular.charmap","name":"iosevka-custom-regular","p...
⡃⢐ Complete 096 - Executing 10 - Pending 158 (36%) ███████▒▒▒▒▒▒▒▒▒▒▒▒▒ | CPU:100% ██████████ - RAM:092% █████████▒<Failure> Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:105:12
    at new Promise (<anonymous>)
    at otfccBuild (/home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:92:9) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-extralight.raw.ttf":
 Error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:105:12
    at new Promise (<anonymous>)
    at otfccBuild (/home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/font-src/index.js:92:9) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
    at ChildProcess.<anonymous> (/home/vp/pkgs/pkgports/os/font_iosevka/lib/Iosevka-dev/node_modules/verda/lib/actions/nodejs/command.js:55:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-oblique.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-oblique.charmap","name":"iosevka-custom-oblique","p...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-italic.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-italic.charmap","name":"iosevka-custom-italic","preH...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-medium.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-medium.charmap","name":"iosevka-custom-medium","preH...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-mediumoblique.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-mediumoblique.charmap","name":"iosevka-custom...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-mediumitalic.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-mediumitalic.charmap","name":"iosevka-custom-m...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-semibold.raw.ttf","oCharMap":".build/ttf/iosevka-custom/iosevka-custom-semibold.charmap","name":"iosevka-custom-semibold"...
× Error Build cancelled by user.
Building process terminated.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@3.6.2 build: `verda -f verdafile.js "contents::iosevka-custom"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iosevka@3.6.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vp/.npm/_logs/2020-10-03T04_43_24_142Z-debug.log
```

**Comment by be5invis** [comment]
Hmm I'd like to simply revert that change. It was wanting to reduce intermediate files...

**Comment by pv4** [comment]
But does it work for _you_ on linux?

**Comment by be5invis** [comment]
@pv4 I do not use Linux to build Iosevka (at least for now).

**Comment by pv4** [comment]
I'm just curious, what do you use? macOS? Windows?

**Comment by be5invis** [comment]
@pv4 Iosevka is built on a Windows PC. I use Linux on other places but not for Iosevka building.
Closing as fixed.
