### ISSUE TITLE
Build fails with "Error: Composite {user} cannot be resolved: j,straight"

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#723]
The building process stops with the error above. I was checking whether the variable I want to use is present and it is indeed -> Readme.md line 518
```     + `j = 'straight'`, `cv18 = 3`: `j` without serif. ```

* Your font version: (Release or git, version)
   git 040c1ff08c3f2e74f68c86ed7ed51bc8d0402bc7
* Your operating system (name and version):
  Gentoo ~amd64
* Your application using Iosevka: everything from terminals up to applications & wm

If you have problem when building Iosevka, please provide these information:
* Your Node.js version:
  v14.15.0
* Your _otfcc_ version:
   This is otfccbuild, version 0.10.4.
* Your `private-build-plans.toml`, if present:
``` [buildPlans.iosevka-artesanal-tailed]
family = "Iosevka Artesanal Tailed"
digit-form = "old-style"
[buildPlans.iosevka-artesanal-tailed.variants.design]
a = "doublestorey-tailed"
d = "tailed"
f = "straight-tailed"
g = "opendoublestorey"
i = "tailed"
j = "straight"
k = "straight"
l = "tailed"
m = "shortleg"
r = "top-serifed"
eszet = "traditional"
t = "flat-hook-short-neck2"
u = "tailed"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
capital-y = "curly"
z = "with-crossbar"
# capital-z = "with-crossbar"
zero = "reverse-slashed"
three = "flattop"
four = "semi-open"
six = "open-contour"
seven = "crossbar"
nine = "open-contour"
ampersand = "flat-top"
bar = "force-upright"
tilde = "high"
asterisk = "high"
paragraph-sign = "high"
caret = "high"
[buildPlans.iosevka-artesanal-tailed.ligations]
inherits = "dlig"
[buildPlans.iosevka-artesanal-tailed.widths.normal]
shape = 500
menu  = 5
css   = "normal"
[buildPlans.iosevka-artesanal-tailed.weights.regular]
shape = 400
menu  = 400
css   = 400
[buildPlans.iosevka-artesanal-tailed.weights.medium]
shape = 500
menu  = 500
css   = 500
[buildPlans.iosevka-artesanal-tailed.weights.semibold]
shape = 600
menu  = 600
css   = 600
[buildPlans.iosevka-artesanal-tailed.weights.bold]
shape = 660
menu  = 700
css   = 700
[buildPlans.iosevka-artesanal-tailed.weights.extrabold]
shape = 800
menu  = 800
css   = 800
[buildPlans.iosevka-artesanal-tailed.weights.heavy]
shape = 900
menu  = 900
css   = 900
[buildPlans.iosevka-artesanal-tailed.slopes]
upright = "normal"
italic = "italic"
```
* The detailed error log:
``` Building process terminated.
Error: Error: Composite {user} cannot be resolved: j,straight.
    at Composite.decompose (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/support/variant-data.js:21:17)
    at reinit (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/index.js:43:15)
    at main (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/font-src/index.js:17:41)
    at ChildProcess.<anonymous> (/usr/local/src/Tools/Iosevka-tools/Iosevka-dev.git/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@4.0.0-alpha.1 build: `verda -f verdafile.js "ttf::iosevka-artesanal-tailed"`
  ```

**Comment by be5invis** [comment]
Some of the variant name just changed recently in dev. README has been updated so you could fix your config.
Closing.

**Comment by wimstefan** [comment]
Thank you so much for your lightning fast response!
All built & well :-D Your font is really amazing with all the possibilities to create your own font *and* the tremendous support you're offering to us mere mortals!!!
I pretty much like the new build system - it's a better structured and very precise in the definitions you can use. The configurability is out of this world!
