### ISSUE TITLE
Private build plan fails 

### ISSUE THREAD

**Issue by dixius99** [be5invis/Iosevka#760]
I'm trying to build 4.0.0 using a private build plan. I can build Iosevka regularly with `npm run build -- contents::iosevka`,  but attempting to build using the contents of the supplied sample and `npm run build -- contents::iosevka-custom`, I get the following:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/michael/.npm/_logs/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/michael/.npm/_logs/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael/.npm/_logs/2020-11-26T18_31_21_808Z-debug.log
```

The full error log is below.

---

* Your font version: (4.0.0)
* Your font variant: default contents of `private.build.plans.toml`
* Your operating system (name and version): macOS 11.0.1
* Your application using Iosevka: N/A

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 15.3.0
* Your _otfcc_ version: stable 0.10.4

* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-custom]      # <iosevka-custom> is your plan name
family = "Iosevka Custom"        # Font menu family name
spacing = "normal"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"                  # Optional; Values: `sans` or `slab`

###################################################################################################
# Configure variants

# Optional; Whether to inherit a `ss##` variant
[buildPlans.iosevka-custom.variants]
inherits = "ss01"

# Optional; Configure single character's variant
[buildPlans.iosevka-custom.variants.design]
g = 'singlestorey'

# Optional; Configure single character's variant for Upright and Oblique; Overrides [design]
[buildPlans.iosevka-custom.variants.upright]
i = 'zshaped'
l = 'zshaped'

# Optional; Configure single character's variant for Italic only; Overrides [design]
[buildPlans.iosevka-custom.variants.italic]
i = 'italic'
l = 'italic'

# End variant section
###################################################################################################

###################################################################################################
# Configure ligations

[buildPlans.iosevka-custom.ligations]
inherits = "default-calt"   # Optional; inherits an existing ligation set
disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
enables  = []               # Optional; enable specific ligation groups, overrides inherited ligation set

# End ligation section
###################################################################################################


###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
[buildPlans.iosevka-custom.weights.regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.iosevka-custom.weights.book]
shape = 450
menu  = 450  # Use 450 here to name the font's weight "Book"
css   = 450

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu  = 700
css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slopes would be built.

[buildPlans.iosevka-custom.slopes]
upright = "normal"
italic = "italic"
oblique = "oblique"

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevka-custom.widths.normal]
shape = 500        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

[buildPlans.iosevka-custom.widths.extended]
shape = 576
menu  = 7
css   = "expanded"

# End width section
###################################################################################################

###################################################################################################
# Character Exclusion
# Specify character ranges in the section below to exclude certain characters from the font being
# built. Remove this section when this feature is not needed.

[buildPlans.iosevka-custom.exclude-chars]
ranges = [[10003, 10008]]

# End character exclusion
###################################################################################################

###################################################################################################
# Compatibility Ligatures
# Certain applications like Emacs does not support proper programming liagtures provided by
# OpenType, but can support ligatures provided by PUA codepoints. Therefore you can edit the
# following section to build PUA characters that are generated from the OpenType ligatures.
# Remove this section when compatibility ligatures are not needed.

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57600 # 0xE100
featureTag = 'calt'
sequence = '<*>'

# End compatibility ligatures section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

[buildPlans.iosevka-custom.metric-override]
leading = 1250
winMetricAscenderPad = 0
winMetricDescenderPad = 0
powerlineScaleY = 1
powerlineScaleX = 1
powerlineShiftY = 0
powerlineShiftX = 0

# End metric override section
###################################################################################################
```
* The detailed error log:
```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.3.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'build',
0 verbose cli   '--',
0 verbose cli   'contents::iosevka-custom'
0 verbose cli ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/michael/.npm/_logs/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/michael/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session 6c9e1848f39c5193
20 timing npm:load Completed in 12ms
21 timing command:run-script Completed in 1ms
22 verbose stack Error: ENOENT: no such file or directory, open '/Users/michael/.npm/_logs/package.json'
23 verbose cwd /Users/michael/.npm/_logs
24 verbose Darwin 20.1.0
25 verbose argv "/usr/local/Cellar/node/15.3.0/bin/node" "/usr/local/bin/npm" "run" "build" "--" "contents::iosevka-custom"
26 verbose node v15.3.0
27 verbose npm  v7.0.14
28 error code ENOENT
29 error syscall open
30 error path /Users/michael/.npm/_logs/package.json
31 error errno -2
32 error enoent ENOENT: no such file or directory, open '/Users/michael/.npm/_logs/package.json'
33 error enoent This is related to npm not being able to find a file.
34 verbose exit -2
```

**Comment by be5invis** [comment]
Um, I think you should `cd` into the repository directory first? It looks like that you are inside a logging directory.

**Comment by dixius99** [comment]
Sorry, I've been going back and forth from different directories. Different error from the repository folder:

```

♦ "utility/make-webfont-css.js" "dist/iosevka-custom/iosevka-custom.css" "Iosevka Custom" [{"name...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-regular.raw.ttf","oCharMap":".b...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-extended.raw.ttf","oCharMap":"....
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-italic.raw.ttf","oCharMap":".bu...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-extendeditalic.raw.ttf","oCharM...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-oblique.raw.ttf","oCharMap":".b...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-extendedoblique.raw.ttf","oChar...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-book.raw.ttf","oCharMap":".buil...
♦ "font-src/index" {"o":".build/ttf/iosevka-custom/iosevka-custom-extendedbook.raw.ttf","oCharMap...
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-italic.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at main (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:17:41)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-extendeditalic.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at main (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:17:41)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-extended.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at Object.para.reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:62:11)
    at r404_createMathDerivedSeriesImpl (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1508:67)
    at r404_CreateMathDerivatives (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1588:16)
    at /Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1611:5
    at Object.r1_apply (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:25:54)
    at r1_buildGlyphs (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/index.js:227:50)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-regular.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at Object.para.reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:62:11)
    at r404_createMathDerivedSeriesImpl (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1508:67)
    at r404_CreateMathDerivatives (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1588:16)
    at /Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1611:5
    at Object.r1_apply (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:25:54)
    at r1_buildGlyphs (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/index.js:227:50)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-extendedbook.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at Object.para.reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:62:11)
    at r404_createMathDerivedSeriesImpl (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1508:67)
    at r404_CreateMathDerivatives (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1588:16)
    at /Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1611:5
    at Object.r1_apply (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:25:54)
    at r1_buildGlyphs (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/index.js:227:50)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-book.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at Object.para.reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:62:11)
    at r404_createMathDerivedSeriesImpl (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1508:67)
    at r404_CreateMathDerivatives (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1588:16)
    at /Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1611:5
    at Object.r1_apply (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:25:54)
    at r1_buildGlyphs (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/index.js:227:50)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-extendedoblique.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at Object.para.reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:62:11)
    at r404_createMathDerivedSeriesImpl (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1508:67)
    at r404_CreateMathDerivatives (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1588:16)
    at /Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1611:5
    at Object.r1_apply (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:25:54)
    at r1_buildGlyphs (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/index.js:227:50)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
× Error Unhandled exception when building "Builtin::File::.build/ttf/iosevka-custom/iosevka-custom-oblique.raw.ttf":
 Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at Object.para.reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:62:11)
    at r404_createMathDerivedSeriesImpl (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1508:67)
    at r404_CreateMathDerivatives (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1588:16)
    at /Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1611:5
    at Object.r1_apply (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:25:54)
    at r1_buildGlyphs (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/index.js:227:50)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Building process terminated.
Error: Error: Composite {user} cannot be resolved: i,italic.
    at Composite.decompose (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:154:19)
    at Composite.resolve (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:166:39)
    at Object.applyVariantData [as apply] (/Users/michael/Downloads/Iosevka-4.0.0/font-src/support/variant-data.js:21:17)
    at reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:43:15)
    at Object.para.reinit (/Users/michael/Downloads/Iosevka-4.0.0/font-src/index.js:62:11)
    at r404_createMathDerivedSeriesImpl (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1508:67)
    at r404_CreateMathDerivatives (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1588:16)
    at /Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:1611:5
    at Object.r1_apply (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/auto-build/transformed.js:25:54)
    at r1_buildGlyphs (/Users/michael/Downloads/Iosevka-4.0.0/font-src/glyphs/index.js:227:50)
    at ChildProcess.<anonymous> (/Users/michael/Downloads/Iosevka-4.0.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:910:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
npm ERR! code 1
npm ERR! path /Users/michael/Downloads/Iosevka-4.0.0
npm ERR! command failed
npm ERR! command sh -c verda -f verdafile.js "contents::iosevka-custom"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael/.npm/_logs/2020-11-26T20_11_02_801Z-debug.log
```

Log:

```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.3.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'build',
0 verbose cli   '--',
0 verbose cli   'contents::iosevka-custom'
0 verbose cli ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/michael/Downloads/Iosevka-4.0.0/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/michael/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 verbose npm-session eefae96d88a0f603
20 timing npm:load Completed in 14ms
21 timing command:run-script Completed in 32922ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1055:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
23 verbose pkgid iosevka@4.0.0
24 verbose cwd /Users/michael/Downloads/Iosevka-4.0.0
25 verbose Darwin 20.1.0
26 verbose argv "/usr/local/Cellar/node/15.3.0/bin/node" "/usr/local/bin/npm" "run" "build" "--" "contents::iosevka-custom"
27 verbose node v15.3.0
28 verbose npm  v7.0.14
29 error code 1
30 error path /Users/michael/Downloads/Iosevka-4.0.0
31 error command failed
32 error command sh -c verda -f verdafile.js "contents::iosevka-custom"
33 verbose exit 1
```

**Comment by be5invis** [comment]
@dixius99 `i` does not have variant `italic` for now. It is now `serifed-tailed`.

**Comment by dixius99** [comment]
Ah, that's better. Thanks Belleve. I didn't even look at the contents of the sample file. Perhaps it can be updated in a future release to only valid options? Might prevent some issues from dummies like me 😛

**Comment by ollet-btatzpety** [comment]
Try adding “`/Iosevka-main`” at the enf of the `/cd` command. Here's the example.
![Image](https://github.com/user-attachments/assets/2d840b8d-c43f-44a8-bab1-c9f388a5f1f2)
