### ISSUE TITLE
Can't turn off variants inherits 

### ISSUE THREAD

**Issue by GalAster** [be5invis/Iosevka#797]
The generated script cannot be run from https://typeof.net/Iosevka/customizer 

---

- `private-build-plans.toml`:

```toml
[buildPlans.iosevka-custom.variants]
inherits = "off" # Comment this line can run
```

![image](https://user-images.githubusercontent.com/17541209/104834546-12b70b00-58db-11eb-8854-966c5e0c77dd.png)

```js
$ npm run build -- contents::iosevka-valkyrie

> iosevka@4.5.0 build D:\Rust\Iosevka-master
> node utility/ensure-verda-exists && verda -f verdafile.js "contents::iosevka-valkyrie"


Error: Error: Cannot find composite variant: off
    at Composite.resolve (D:\Rust\Iosevka-master\font-src\support\variant-data.js:165:11)
    at Object.applyVariantData [as apply] (D:\Rust\Iosevka-master\font-src\support\variant-data.js:21:17)
    at reinit (D:\Rust\Iosevka-master\font-src\index.js:43:15)
    at main (D:\Rust\Iosevka-master\font-src\index.js:17:41)
    at ChildProcess.<anonymous> (D:\Rust\Iosevka-master\node_modules\verda\lib\actions\nodejs\command.js:53:31)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@4.5.0 build: `node utility/ensure-verda-exists && verda -f verdafile.js "contents::iosevka-valkyrie"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iosevka@4.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-01-17T07_36_44_406Z-debug.log
```

**Comment by be5invis** [comment]
The customizer has been updated so there won't be anymore `inherits = 'off'`. From the building system point of view, this **should** be considered invalid.
Closing.
