### ISSUE TITLE
Mac OS X build failure

### ISSUE THREAD

**Issue by bitserf** [be5invis/Iosevka#88]
Hello,

I haven't build Iosevka for a while...Recently when I tried it, I encountered some problems.
I started from scratch (clean checkout from GitHub).

**Versions:**
```shell
$ node --version
v5.11.1

$ otfccbuild --version
This is otfccbuild, version 0.1.8.

$ ttfautohint --version
ttfautohint 1.5
Copyright (C) 2011-2016 Werner Lemberg <wl@gnu.org>.
License: FreeType License (FTL) or GNU GPLv2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 17:57 NZST  3-Jun-2016-D.
 Based on source from git with hash:
fontforge 17:57 NZST  3-Jun-2016
libfontforge 20160603
```

I made sure node is version with full ICU support.

My shell command is custom, because I want the lower underscore.

**Build:**
```shell
$ npm install
├── bezier-js@2.0.0
├── cubic2quad@1.0.0
├── libspiro-js@0.3.1
├─┬ patel@0.30.5
│ ├─┬ escodegen@1.8.0
│ │ ├── esprima@2.7.2
│ │ ├── estraverse@1.9.3
│ │ ├── esutils@2.0.2
│ │ ├─┬ optionator@0.8.1
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@1.1.3
│ │ │ ├── levn@0.3.0
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├── type-check@0.3.2
│ │ │ └── wordwrap@1.0.0
│ │ └─┬ source-map@0.2.0
│ │   └── amdefine@1.0.0
│ ├─┬ esmangle@1.0.1
│ │ ├── escodegen@1.3.3
│ │ ├─┬ escope@1.0.3
│ │ │ └── estraverse@2.0.0
│ │ ├── esprima@1.1.1
│ │ ├─┬ esshorten@1.1.1
│ │ │ └── estraverse@4.1.1
│ │ ├── estraverse@1.5.1
│ │ ├── esutils@1.0.0
│ │ ├─┬ optionator@0.3.0
│ │ │ ├── fast-levenshtein@1.0.7
│ │ │ ├── levn@0.2.5
│ │ │ └── wordwrap@0.0.3
│ │ └── source-map@0.1.43
│ ├── patrisika@0.20.2
│ ├── patrisika-scopes@0.11.0
│ └─┬ resumer@0.0.0
│   └── through@2.3.8
├── toml@2.3.0
├── unorm@1.4.1
└─┬ yargs@4.7.1
  ├── camelcase@3.0.0
  ├─┬ cliui@3.2.0
  │ ├─┬ strip-ansi@3.0.1
  │ │ └── ansi-regex@2.0.0
  │ └── wrap-ansi@2.0.0
  ├── decamelize@1.2.0
  ├─┬ lodash.assign@4.0.9
  │ ├── lodash.keys@4.0.7
  │ └── lodash.rest@4.0.3
  ├─┬ os-locale@1.4.0
  │ └─┬ lcid@1.0.0
  │   └── invert-kv@1.0.0
  ├─┬ pkg-conf@1.1.3
  │ ├─┬ find-up@1.1.2
  │ │ ├── path-exists@2.1.0
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ load-json-file@1.1.0
  │ │ ├── graceful-fs@4.1.4
  │ │ ├─┬ parse-json@2.2.0
  │ │ │ └─┬ error-ex@1.3.0
  │ │ │   └── is-arrayish@0.2.1
  │ │ ├── pify@2.3.0
  │ │ └─┬ strip-bom@2.0.0
  │ │   └── is-utf8@0.2.1
  │ ├── object-assign@4.1.0
  │ └── symbol@0.2.3
  ├─┬ read-pkg-up@1.0.1
  │ └─┬ read-pkg@1.1.0
  │   ├─┬ normalize-package-data@2.3.5
  │   │ ├── hosted-git-info@2.1.5
  │   │ ├─┬ is-builtin-module@1.0.0
  │   │ │ └── builtin-modules@1.1.1
  │   │ ├── semver@5.1.0
  │   │ └─┬ validate-npm-package-license@3.0.1
  │   │   ├─┬ spdx-correct@1.0.2
  │   │   │ └── spdx-license-ids@1.2.1
  │   │   └─┬ spdx-expression-parse@1.0.2
  │   │     └── spdx-exceptions@1.0.4
  │   └── path-type@1.1.0
  ├── require-main-filename@1.0.1
  ├── set-blocking@1.0.0
  ├─┬ string-width@1.0.1
  │ ├─┬ code-point-at@1.0.0
  │ │ └── number-is-nan@1.0.0
  │ └── is-fullwidth-code-point@1.0.0
  ├── window-size@0.2.0
  ├── y18n@3.2.1
  └─┬ yargs-parser@2.4.0
    └── camelcase@2.1.1

npm WARN iosevka@1.8.4 No repository field.
npm WARN iosevka@1.8.4 No license field.

$ make STYLE_COMMON='v-tilde-low v-asterisk-low v-underscore-low'
node ./node_modules/patel/bin/patel-c --optimize --strict support/glyph.ptl -o support/glyph.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/spiroexpand.ptl -o support/spiroexpand.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/spirokit.ptl -o support/spirokit.js
node ./node_modules/patel/bin/patel-c --optimize --strict parameters.ptl -o parameters.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/anchor.ptl -o support/anchor.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/point.ptl -o support/point.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/transform.ptl -o support/transform.js
node ./node_modules/patel/bin/patel-c --strict buildglyphs.ptl -o buildglyphs.js
RangeError: Maximum call stack size exceeded
    at /Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:815:12
    at ret$ (/Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:812:28)
    at /Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:814:11
    at Object.<anonymous> (/Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:585:36)
    at /Users/ljb/Code/Iosevka/node_modules/patrisika/commons/match.js:74:79
    at ret$ (/Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:813:10)
    at /Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:814:11
    at Object.<anonymous> (/Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:585:36)
    at /Users/ljb/Code/Iosevka/node_modules/patrisika/commons/match.js:74:79
    at ret$ (/Users/ljb/Code/Iosevka/node_modules/patrisika/passes/cps-deo.js:813:10)
/Applications/Xcode.app/Contents/Developer/usr/bin/make fonts config=d-sans
    Start building font Iosevka Thin 1.8.5 (Hermandine)
/Users/ljb/Code/Iosevka/generator.js:26
	var font = buildGlyphs.build.call(emptyFont, para);
	                            ^

TypeError: Cannot read property 'call' of undefined
    at /Users/ljb/Code/Iosevka/generator.js:26:30
    at Object.<anonymous> (/Users/ljb/Code/Iosevka/generator.js:36:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
make[2]: *** [build/.pass0-iosevka-thin.fdt] Error 1
make[1]: *** [fonts] Error 2
make: *** [fonts-d-sans] Error 2
```

It looks somehow like patel error? But I tried 0.30.0 (previous version), same result.

Any hints?
Thanks!

Leon

**Comment by be5invis** [comment]
You can try to increase memory limit used in `node ./node_modules/patel/bin/patel-c` step. You know, `buildglyphs.js` is huge.

**Comment by bitserf** [comment]
Thanks - I can confirm that made it build.

**Comment by bitserf** [comment]
Spoke too soon: Fails on iosevka-thin-italic:

```shell
/Users/ljb/Code/Iosevka/support/glyph.js:120
                    r285_point = r285_contour[r285_j], r285_point.onCurve ? (r285_delta ? r285_buf += 'l ' + r1_cov(r285_point.x - r285_lx) + ' ' + r1_cov(r285_point.y - r285_ly) : r285_buf += 'L ' + r1_cov(r285_point.x) + ' ' + r1_cov(r285_point.y), _r285_t2 = r285_point, r285_lx = _r285_t2.x, r285_ly = _r285_t2.y) : r285_point.cubic ? (r285_z1 = r285_point, r285_z2 = r285_contour[r285_j + 1], r285_z3 = r285_contour[r285_j + 2], r285_delta ? r285_buf += 'c ' + r1_cov(r285_z1.x - r285_lx) + ' ' + r1_cov(r285_z1.y - r285_ly) + ' ' + r1_cov(r285_z2.x - r285_lx) + ' ' + r1_cov(r285_z2.y - r285_ly) + ' ' + r1_cov(r285_z3.x - r285_lx) + ' ' + r1_cov(r285_z3.y - r285_ly) : r285_buf += 'C ' + r1_cov(r285_z1.x) + ' ' + r1_cov(r285_z1.y) + ' ' + r1_cov(r285_z2.x) + ' ' + r1_cov(r285_z2.y) + ' ' + r1_cov(r285_z3.x) + ' ' + r1_cov(r285_z3.y), _r285_t1 = r285_z3, r285_lx = _r285_t1.x, r285_ly = _r285_t1.y, r285_j += 2) : (r285_zc = r285_point, r285_zf = r285_contour[rmake[2]: *** [build/.pass0-iosevka-thinitalic.fdt] Error 1
make[1]: *** [fonts] Error 2
make: *** [fonts-d-sans] Error 2
```

**Comment by be5invis** [comment]
@bitserf Is the latest commit fixed that?

**Comment by bitserf** [comment]
It is fixed. Thank you! :+1:

I found a separate issue with cv21 (_v-underscore-low_), but I will open a different issue for it, the build problem is gone.
